import Credential from '../features/credential/credential.model.js';
import { SEED_IDS } from './users.js';

// Helper to generate past dates
const daysAgo = (days) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date;
};

const monthsAgo = (months) => {
  const date = new Date();
  date.setMonth(date.getMonth() - months);
  return date;
};

// Demo certificate image URL (consistent across all certificates for demo purposes)
const DEMO_CERT_IMAGE = 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&h=600&fit=crop&q=80';

// 5 Credentials for Priya Sharma (demo learner)
const credentials = [
  // VERIFIED #1 - Coursera Certificate
  {
    user: SEED_IDS.learner1,
    legalNameSnapshot: 'Priya Sharma',
    certificateName: 'Priya Sharma',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 95,
    autoApproved: true,
    title: 'Machine Learning Specialization',
    issuer: 'Coursera - Stanford University',
    issueDate: monthsAgo(8),
    type: 'certificate',
    credentialId: 'COURSERA-ML-2024-PS123',
    totalHours: 120,
    skills: ['Machine Learning', 'Python', 'Neural Networks', 'TensorFlow', 'Supervised Learning'],
    description: 'Comprehensive machine learning specialization covering supervised learning, neural networks, and deep learning. Completed 3-course series with hands-on projects.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'coursera-ml-certificate.jpg',
      fileType: 'image/jpeg',
      uploadedAt: monthsAgo(8),
    },
    sourceUrl: 'https://www.coursera.org/account/accomplishments/specialization/ABC123XYZ',
    sourceDomain: 'coursera.org',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verificationNotes: 'Certificate verified through Coursera official API. All metadata confirmed valid.',
    meta: {
      platform: 'Coursera',
      verificationMethod: 'api_verified',
      courseCount: 3,
    },
    createdAt: monthsAgo(8),
    updatedAt: daysAgo(5)
  },
  // VERIFIED #2 - Degree Certificate
  {
    user: SEED_IDS.learner1,
    legalNameSnapshot: 'Priya Sharma',
    certificateName: 'Priya Sharma',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 98,
    autoApproved: true,
    title: 'Bachelor of Technology - Computer Science',
    issuer: 'Indian Institute of Technology Delhi',
    issueDate: new Date('2019-06-15'),
    type: 'degree',
    credentialId: 'IIT-DEL-CS-2019-456',
    skills: ['Computer Science', 'Algorithms', 'Data Structures', 'DBMS', 'Operating Systems', 'Computer Networks'],
    description: 'Bachelor of Technology degree in Computer Science and Engineering from IIT Delhi. Graduated with honors.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'btech-degree-iitdelhi.pdf',
      fileType: 'application/pdf',
      uploadedAt: monthsAgo(6),
    },
    sourceUrl: 'https://home.iitd.ac.in/verify/degree/2019CS456',
    sourceDomain: 'iitd.ac.in',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verificationNotes: 'Degree verified with IIT Delhi registrar office. Student ID and graduation year confirmed.',
    meta: {
      graduationYear: 2019,
      cgpa: 8.5,
      honors: true,
      department: 'Computer Science and Engineering',
    },
    createdAt: monthsAgo(6),
    updatedAt: daysAgo(10)
  },
  // VERIFIED #3 - AWS Developer Certification
  {
    user: SEED_IDS.learner1,
    legalNameSnapshot: 'Priya Sharma',
    certificateName: 'Priya Sharma',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 92,
    autoApproved: true,
    title: 'AWS Certified Developer - Associate',
    issuer: 'Amazon Web Services',
    issueDate: monthsAgo(2),
    type: 'certificate',
    credentialId: 'AWS-DEV-2024-321',
    totalHours: 40,
    skills: ['AWS', 'Lambda', 'DynamoDB', 'API Gateway', 'CloudFormation', 'S3'],
    description: 'AWS certification for developers building and maintaining applications on AWS platform. Covers core AWS services and best practices.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'aws-developer-cert.pdf',
      fileType: 'application/pdf',
      uploadedAt: daysAgo(15),
    },
    sourceUrl: 'https://aws.amazon.com/certification/certified-developer-associate/',
    sourceDomain: 'aws.amazon.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verificationNotes: 'Certificate automatically verified. Name matches, trusted domain, valid credential ID.',
    meta: {
      expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 3)),
    },
    createdAt: daysAgo(15),
    updatedAt: daysAgo(15)
  },
  // VERIFIED #4 - Full Stack Web Development
  {
    user: SEED_IDS.learner1,
    legalNameSnapshot: 'Priya Sharma',
    certificateName: 'Priya Sharma',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 90,
    autoApproved: true,
    title: 'Full Stack Web Development Bootcamp',
    issuer: 'Udemy',
    issueDate: monthsAgo(1),
    type: 'micro_credential',
    credentialId: 'UC-FULLSTACK-2024-654',
    totalHours: 80,
    skills: ['React', 'Node.js', 'Express', 'MongoDB', 'JavaScript', 'HTML', 'CSS', 'REST API'],
    description: 'Comprehensive full-stack development bootcamp covering MERN stack. Completed with 50+ hands-on projects and real-world applications.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'udemy-fullstack-cert.pdf',
      fileType: 'application/pdf',
      uploadedAt: daysAgo(7),
    },
    sourceUrl: 'https://www.udemy.com/certificate/UC-FULLSTACK-2024-654/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verificationNotes: 'Certificate automatically verified. Name matches, trusted domain, valid credential format.',
    meta: {
      completionRate: 100,
      projectCount: 52,
      rating: 4.8,
    },
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7)
  },

  // ============================================
  // MORE VERIFIED COURSES FOR PRIYA SHARMA (learner1)
  // ============================================

  // COURSE - React Advanced Concepts (All Learners)
  // learner1
  {
    user: SEED_IDS.learner1,
    legalNameSnapshot: 'Priya Sharma',
    certificateName: 'Priya Sharma',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 96,
    autoApproved: true,
    title: 'Advanced React: Hooks, Context, and Performance',
    issuer: 'Udemy',
    issueDate: monthsAgo(4),
    type: 'certificate',
    credentialId: 'UC-REACT-ADV-2024-101',
    totalHours: 45,
    nsqfLevel: 6,
    skills: ['React', 'React Hooks', 'Context API', 'Performance Optimization', 'Redux'],
    description: 'Advanced React course covering hooks, context, performance optimization, and state management patterns.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'react-advanced-cert.pdf',
      fileType: 'application/pdf',
      uploadedAt: monthsAgo(4),
    },
    sourceUrl: 'https://www.udemy.com/certificate/UC-REACT-ADV-2024-101/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(3),
    meta: {
      platform: 'Udemy',
      category: 'Web Development',
      rating: 4.8,
    },
    createdAt: monthsAgo(4),
    updatedAt: monthsAgo(3)
  },

  // COURSE - Cloud Computing Fundamentals (learner1)
  {
    user: SEED_IDS.learner1,
    legalNameSnapshot: 'Priya Sharma',
    certificateName: 'Priya Sharma',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 94,
    autoApproved: true,
    title: 'Introduction to Cloud Computing',
    issuer: 'Coursera - IBM',
    issueDate: monthsAgo(5),
    type: 'certificate',
    credentialId: 'COURSERA-CLOUD-2024-102',
    totalHours: 60,
    nsqfLevel: 5,
    skills: ['Cloud Computing', 'AWS', 'Azure', 'GCP', 'Cloud Architecture'],
    description: 'Comprehensive introduction to cloud computing covering major platforms, architectures, and deployment models.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'cloud-computing-cert.jpg',
      fileType: 'image/jpeg',
      uploadedAt: monthsAgo(5),
    },
    sourceUrl: 'https://www.coursera.org/account/accomplishments/certificate/CLOUD-2024-102',
    sourceDomain: 'coursera.org',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(4),
    meta: {
      platform: 'Coursera',
      category: 'Cloud Computing',
      university: 'IBM',
    },
    createdAt: monthsAgo(5),
    updatedAt: monthsAgo(4)
  },

  // COURSE - Docker & Kubernetes (learner1)
  {
    user: SEED_IDS.learner1,
    legalNameSnapshot: 'Priya Sharma',
    certificateName: 'Priya Sharma',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 97,
    autoApproved: true,
    title: 'Docker and Kubernetes: The Complete Guide',
    issuer: 'Udemy',
    issueDate: monthsAgo(3),
    type: 'certificate',
    credentialId: 'UC-DOCKER-K8S-2024-103',
    totalHours: 75,
    nsqfLevel: 7,
    skills: ['Docker', 'Kubernetes', 'Containerization', 'DevOps', 'Microservices'],
    description: 'Complete guide to containerization with Docker and orchestration with Kubernetes. Includes hands-on projects.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'docker-kubernetes-cert.pdf',
      fileType: 'application/pdf',
      uploadedAt: monthsAgo(3),
    },
    sourceUrl: 'https://www.udemy.com/certificate/UC-DOCKER-K8S-2024-103/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(2),
    meta: {
      platform: 'Udemy',
      category: 'DevOps',
      rating: 4.9,
      projectCount: 12,
    },
    createdAt: monthsAgo(3),
    updatedAt: monthsAgo(2)
  },

  // COURSE - Data Structures & Algorithms (learner1)
  {
    user: SEED_IDS.learner1,
    legalNameSnapshot: 'Priya Sharma',
    certificateName: 'Priya Sharma',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 98,
    autoApproved: true,
    title: 'Data Structures and Algorithms Masterclass',
    issuer: 'edX - UC San Diego',
    issueDate: monthsAgo(9),
    type: 'certificate',
    credentialId: 'EDX-DSA-2024-104',
    totalHours: 100,
    nsqfLevel: 7,
    skills: ['Data Structures', 'Algorithms', 'Problem Solving', 'Coding Interview', 'Big O Notation'],
    description: 'Comprehensive course on data structures and algorithms with focus on problem-solving and coding interviews.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'dsa-masterclass-cert.pdf',
      fileType: 'application/pdf',
      uploadedAt: monthsAgo(9),
    },
    sourceUrl: 'https://courses.edx.org/certificates/EDX-DSA-2024-104',
    sourceDomain: 'edx.org',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(8),
    meta: {
      platform: 'edX',
      category: 'Computer Science',
      university: 'UC San Diego',
    },
    createdAt: monthsAgo(9),
    updatedAt: monthsAgo(8)
  },

  // COURSE - TypeScript Programming (learner1)
  {
    user: SEED_IDS.learner1,
    legalNameSnapshot: 'Priya Sharma',
    certificateName: 'Priya Sharma',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 95,
    autoApproved: true,
    title: 'TypeScript: The Complete Developer\'s Guide',
    issuer: 'Udemy',
    issueDate: monthsAgo(6),
    type: 'micro_credential',
    credentialId: 'UC-TS-2024-105',
    totalHours: 40,
    nsqfLevel: 6,
    skills: ['TypeScript', 'JavaScript', 'Type Systems', 'Object-Oriented Programming'],
    description: 'Complete TypeScript course covering type systems, generics, decorators, and integration with popular frameworks.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'typescript-cert.jpg',
      fileType: 'image/jpeg',
      uploadedAt: monthsAgo(6),
    },
    sourceUrl: 'https://www.udemy.com/certificate/UC-TS-2024-105/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(5),
    meta: {
      platform: 'Udemy',
      category: 'Programming',
      rating: 4.7,
    },
    createdAt: monthsAgo(6),
    updatedAt: monthsAgo(5)
  },

  // COURSE - GraphQL & Apollo (learner1)
  {
    user: SEED_IDS.learner1,
    legalNameSnapshot: 'Priya Sharma',
    certificateName: 'Priya Sharma',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 93,
    autoApproved: true,
    title: 'GraphQL with Apollo and React',
    issuer: 'LinkedIn Learning',
    issueDate: monthsAgo(2),
    type: 'micro_credential',
    credentialId: 'LIL-GRAPHQL-2024-106',
    totalHours: 25,
    nsqfLevel: 5,
    skills: ['GraphQL', 'Apollo Client', 'Apollo Server', 'React', 'API Design'],
    description: 'Modern GraphQL course covering schema design, queries, mutations, and integration with React.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'graphql-apollo-cert.pdf',
      fileType: 'application/pdf',
      uploadedAt: monthsAgo(2),
    },
    sourceUrl: 'https://www.linkedin.com/learning/certificates/GRAPHQL-2024-106',
    sourceDomain: 'linkedin.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(1),
    meta: {
      platform: 'LinkedIn Learning',
      category: 'Web Development',
    },
    createdAt: monthsAgo(2),
    updatedAt: monthsAgo(1)
  },

  // COURSE - System Design (learner1)
  {
    user: SEED_IDS.learner1,
    legalNameSnapshot: 'Priya Sharma',
    certificateName: 'Priya Sharma',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 99,
    autoApproved: true,
    title: 'System Design and Architecture Fundamentals',
    issuer: 'Coursera - University of Alberta',
    issueDate: monthsAgo(7),
    type: 'certificate',
    credentialId: 'COURSERA-SYS-2024-107',
    totalHours: 90,
    nsqfLevel: 8,
    skills: ['System Design', 'Software Architecture', 'Scalability', 'Distributed Systems', 'Microservices'],
    description: 'Advanced course on system design covering scalability, reliability, and distributed systems architecture.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'system-design-cert.jpg',
      fileType: 'image/jpeg',
      uploadedAt: monthsAgo(7),
    },
    sourceUrl: 'https://www.coursera.org/account/accomplishments/certificate/SYS-2024-107',
    sourceDomain: 'coursera.org',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(6),
    meta: {
      platform: 'Coursera',
      category: 'Software Engineering',
      university: 'University of Alberta',
    },
    createdAt: monthsAgo(7),
    updatedAt: monthsAgo(6)
  },

  // COURSE - MongoDB Developer (learner1)
  {
    user: SEED_IDS.learner1,
    legalNameSnapshot: 'Priya Sharma',
    certificateName: 'Priya Sharma',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 92,
    autoApproved: true,
    title: 'MongoDB - The Complete Developer\'s Guide',
    issuer: 'Udemy',
    issueDate: monthsAgo(10),
    type: 'micro_credential',
    credentialId: 'UC-MONGO-2024-108',
    totalHours: 55,
    nsqfLevel: 5,
    skills: ['MongoDB', 'NoSQL', 'Database Design', 'Aggregation', 'Node.js'],
    description: 'Complete MongoDB course covering CRUD operations, aggregation framework, indexing, and performance optimization.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'mongodb-cert.pdf',
      fileType: 'application/pdf',
      uploadedAt: monthsAgo(10),
    },
    sourceUrl: 'https://www.udemy.com/certificate/UC-MONGO-2024-108/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(9),
    meta: {
      platform: 'Udemy',
      category: 'Database',
      rating: 4.6,
    },
    createdAt: monthsAgo(10),
    updatedAt: monthsAgo(9)
  },

  // COURSE - Git & GitHub (learner1)
  {
    user: SEED_IDS.learner1,
    legalNameSnapshot: 'Priya Sharma',
    certificateName: 'Priya Sharma',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 91,
    autoApproved: true,
    title: 'Git & GitHub Complete Master Class',
    issuer: 'LinkedIn Learning',
    issueDate: monthsAgo(11),
    type: 'micro_credential',
    credentialId: 'LIL-GIT-2024-109',
    totalHours: 20,
    nsqfLevel: 4,
    skills: ['Git', 'GitHub', 'Version Control', 'Collaboration', 'CI/CD'],
    description: 'Master class on Git and GitHub covering branching strategies, collaboration workflows, and GitHub Actions.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'git-github-cert.jpg',
      fileType: 'image/jpeg',
      uploadedAt: monthsAgo(11),
    },
    sourceUrl: 'https://www.linkedin.com/learning/certificates/GIT-2024-109',
    sourceDomain: 'linkedin.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(10),
    meta: {
      platform: 'LinkedIn Learning',
      category: 'DevOps',
    },
    createdAt: monthsAgo(11),
    updatedAt: monthsAgo(10)
  },

  // COURSE - RESTful API Design (learner1)
  {
    user: SEED_IDS.learner1,
    legalNameSnapshot: 'Priya Sharma',
    certificateName: 'Priya Sharma',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 94,
    autoApproved: true,
    title: 'RESTful API Design and Development',
    issuer: 'Udemy',
    issueDate: monthsAgo(12),
    type: 'certificate',
    credentialId: 'UC-REST-API-2024-110',
    totalHours: 50,
    nsqfLevel: 6,
    skills: ['REST API', 'API Design', 'Node.js', 'Express', 'Authentication', 'Swagger'],
    description: 'Comprehensive course on designing and building RESTful APIs with best practices, security, and documentation.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'restful-api-cert.pdf',
      fileType: 'application/pdf',
      uploadedAt: monthsAgo(12),
    },
    sourceUrl: 'https://www.udemy.com/certificate/UC-REST-API-2024-110/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(11),
    meta: {
      platform: 'Udemy',
      category: 'Backend Development',
      rating: 4.8,
    },
    createdAt: monthsAgo(12),
    updatedAt: monthsAgo(11)
  },

  // ============================================
  // RECOMMENDED COURSES - VERIFIED (12 courses for various learners)
  // ============================================

  // COURSE #1 - Python for Data Science (learner2)
  {
    user: SEED_IDS.learner2,
    legalNameSnapshot: 'Rahul Kumar',
    certificateName: 'Rahul Kumar',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 94,
    autoApproved: true,
    title: 'Python for Data Science and Machine Learning',
    issuer: 'Coursera - University of Michigan',
    issueDate: monthsAgo(5),
    type: 'certificate',
    credentialId: 'COURSERA-PY-DS-2024-001',
    totalHours: 80,
    nsqfLevel: 5,
    skills: ['Python', 'Data Science', 'Pandas', 'NumPy', 'Data Visualization', 'Jupyter'],
    description: 'Comprehensive course on data science fundamentals using Python. Covers pandas, numpy, matplotlib, and machine learning basics.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'python-datascience-cert.jpg',
      fileType: 'image/jpeg',
      uploadedAt: monthsAgo(5),
    },
    sourceUrl: 'https://www.coursera.org/account/accomplishments/certificate/PY-DS-001',
    sourceDomain: 'coursera.org',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(4),
    meta: {
      platform: 'Coursera',
      category: 'Data Science',
    },
    createdAt: monthsAgo(5),
    updatedAt: monthsAgo(4)
  },

  // COURSE #2 - Digital Marketing (learner3)
  {
    user: SEED_IDS.learner3,
    legalNameSnapshot: 'Ananya Patel',
    certificateName: 'Ananya Patel',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 91,
    autoApproved: true,
    title: 'Digital Marketing Masterclass - 23 Courses in 1',
    issuer: 'Udemy',
    issueDate: monthsAgo(3),
    type: 'micro_credential',
    credentialId: 'UC-DM-MC-2024-002',
    totalHours: 40,
    nsqfLevel: 4,
    skills: ['Digital Marketing', 'SEO', 'Social Media Marketing', 'Email Marketing', 'Content Marketing'],
    description: 'Complete digital marketing course covering SEO, social media, email marketing, and analytics.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'digital-marketing-cert.pdf',
      fileType: 'application/pdf',
      uploadedAt: monthsAgo(3),
    },
    sourceUrl: 'https://www.udemy.com/certificate/UC-DM-MC-2024-002/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(2),
    meta: {
      platform: 'Udemy',
      category: 'Marketing',
      rating: 4.7,
    },
    createdAt: monthsAgo(3),
    updatedAt: monthsAgo(2)
  },

  // COURSE #3 - UI/UX Design (learner4)
  {
    user: SEED_IDS.learner4,
    legalNameSnapshot: 'Vikram Singh',
    certificateName: 'Vikram Singh',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 96,
    autoApproved: true,
    title: 'UI/UX Design Fundamentals',
    issuer: 'Udemy',
    issueDate: monthsAgo(4),
    type: 'certificate',
    credentialId: 'UC-UIUX-2024-003',
    totalHours: 60,
    nsqfLevel: 5,
    skills: ['UI Design', 'UX Design', 'Figma', 'Wireframing', 'Prototyping', 'User Research'],
    description: 'Complete UI/UX design course covering design principles, Figma, wireframing, and user testing.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'uiux-design-cert.jpg',
      fileType: 'image/jpeg',
      uploadedAt: monthsAgo(4),
    },
    sourceUrl: 'https://www.udemy.com/certificate/UC-UIUX-2024-003/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(3),
    meta: {
      platform: 'Udemy',
      category: 'Design',
      projectCount: 15,
    },
    createdAt: monthsAgo(4),
    updatedAt: monthsAgo(3)
  },

  // COURSE #4 - AWS Solutions Architect (learner5)
  {
    user: SEED_IDS.learner5,
    legalNameSnapshot: 'Sneha Reddy',
    certificateName: 'Sneha Reddy',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 97,
    autoApproved: true,
    title: 'AWS Certified Solutions Architect - Associate',
    issuer: 'Amazon Web Services',
    issueDate: monthsAgo(6),
    type: 'certificate',
    credentialId: 'AWS-SA-2024-004',
    totalHours: 100,
    nsqfLevel: 6,
    skills: ['AWS', 'Cloud Architecture', 'EC2', 'S3', 'VPC', 'IAM'],
    description: 'AWS certification for designing distributed systems on AWS. Covers core AWS services and best practices.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'aws-solutions-architect.pdf',
      fileType: 'application/pdf',
      uploadedAt: monthsAgo(6),
    },
    sourceUrl: 'https://aws.amazon.com/certification/certified-solutions-architect-associate/',
    sourceDomain: 'aws.amazon.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(5),
    meta: {
      platform: 'AWS',
      category: 'Cloud Computing',
      expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 3)),
    },
    createdAt: monthsAgo(6),
    updatedAt: monthsAgo(5)
  },

  // COURSE #5 - Product Management (learner6)
  {
    user: SEED_IDS.learner6,
    legalNameSnapshot: 'Arjun Mehta',
    certificateName: 'Arjun Mehta',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 92,
    autoApproved: true,
    title: 'Product Management Essentials',
    issuer: 'LinkedIn Learning',
    issueDate: monthsAgo(2),
    type: 'micro_credential',
    credentialId: 'LIL-PM-2024-005',
    totalHours: 30,
    nsqfLevel: 5,
    skills: ['Product Management', 'Agile', 'User Stories', 'Product Strategy', 'Roadmapping'],
    description: 'Essential product management skills including strategy, roadmapping, and agile methodologies.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'product-mgmt-cert.jpg',
      fileType: 'image/jpeg',
      uploadedAt: monthsAgo(2),
    },
    sourceUrl: 'https://www.linkedin.com/learning/certificates/PM-2024-005',
    sourceDomain: 'linkedin.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(1),
    meta: {
      platform: 'LinkedIn Learning',
      category: 'Business',
    },
    createdAt: monthsAgo(2),
    updatedAt: monthsAgo(1)
  },

  // COURSE #6 - Full Stack JavaScript (learner7)
  {
    user: SEED_IDS.learner7,
    legalNameSnapshot: 'Kavya Iyer',
    certificateName: 'Kavya Iyer',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 95,
    autoApproved: true,
    title: 'Full Stack JavaScript Development',
    issuer: 'edX - MIT',
    issueDate: monthsAgo(7),
    type: 'certificate',
    credentialId: 'EDX-FSJS-2024-006',
    totalHours: 150,
    nsqfLevel: 6,
    skills: ['JavaScript', 'React', 'Node.js', 'Express', 'MongoDB', 'REST API'],
    description: 'Comprehensive full-stack JavaScript course covering MERN stack development and deployment.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'fullstack-js-cert.pdf',
      fileType: 'application/pdf',
      uploadedAt: monthsAgo(7),
    },
    sourceUrl: 'https://courses.edx.org/certificates/EDX-FSJS-2024-006',
    sourceDomain: 'edx.org',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(6),
    meta: {
      platform: 'edX',
      category: 'Technology',
      university: 'MIT',
    },
    createdAt: monthsAgo(7),
    updatedAt: monthsAgo(6)
  },

  // COURSE #7 - Blockchain Fundamentals (learner2)
  {
    user: SEED_IDS.learner2,
    legalNameSnapshot: 'Rahul Kumar',
    certificateName: 'Rahul Kumar',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 93,
    autoApproved: true,
    title: 'Blockchain Fundamentals',
    issuer: 'Coursera - University of Buffalo',
    issueDate: monthsAgo(4),
    type: 'certificate',
    credentialId: 'COURSERA-BC-2024-007',
    totalHours: 50,
    nsqfLevel: 5,
    skills: ['Blockchain', 'Cryptocurrency', 'Smart Contracts', 'Ethereum', 'Distributed Systems'],
    description: 'Introduction to blockchain technology, cryptocurrencies, and smart contracts development.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'blockchain-cert.jpg',
      fileType: 'image/jpeg',
      uploadedAt: monthsAgo(4),
    },
    sourceUrl: 'https://www.coursera.org/account/accomplishments/certificate/BC-2024-007',
    sourceDomain: 'coursera.org',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(3),
    meta: {
      platform: 'Coursera',
      category: 'Technology',
    },
    createdAt: monthsAgo(4),
    updatedAt: monthsAgo(3)
  },

  // COURSE #8 - Machine Learning A-Z (learner3)
  {
    user: SEED_IDS.learner3,
    legalNameSnapshot: 'Ananya Patel',
    certificateName: 'Ananya Patel',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 98,
    autoApproved: true,
    title: 'Machine Learning A-Z: Hands-On Python & R',
    issuer: 'Udemy',
    issueDate: monthsAgo(8),
    type: 'certificate',
    credentialId: 'UC-ML-AZ-2024-008',
    totalHours: 120,
    nsqfLevel: 7,
    skills: ['Machine Learning', 'Python', 'R', 'Deep Learning', 'Neural Networks', 'TensorFlow'],
    description: 'Advanced machine learning course covering supervised and unsupervised learning, deep learning, and neural networks.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'ml-az-cert.pdf',
      fileType: 'application/pdf',
      uploadedAt: monthsAgo(8),
    },
    sourceUrl: 'https://www.udemy.com/certificate/UC-ML-AZ-2024-008/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(7),
    meta: {
      platform: 'Udemy',
      category: 'Data Science',
      rating: 4.9,
    },
    createdAt: monthsAgo(8),
    updatedAt: monthsAgo(7)
  },

  // COURSE #9 - Agile Project Management (learner4)
  {
    user: SEED_IDS.learner4,
    legalNameSnapshot: 'Vikram Singh',
    certificateName: 'Vikram Singh',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 90,
    autoApproved: true,
    title: 'Agile Project Management Professional',
    issuer: 'Udemy',
    issueDate: monthsAgo(2),
    type: 'micro_credential',
    credentialId: 'UC-AGILE-2024-009',
    totalHours: 35,
    nsqfLevel: 4,
    skills: ['Agile', 'Scrum', 'Project Management', 'Sprint Planning', 'Kanban'],
    description: 'Agile project management certification covering Scrum, Kanban, and agile best practices.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'agile-pm-cert.jpg',
      fileType: 'image/jpeg',
      uploadedAt: monthsAgo(2),
    },
    sourceUrl: 'https://www.udemy.com/certificate/UC-AGILE-2024-009/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(1),
    meta: {
      platform: 'Udemy',
      category: 'Business',
    },
    createdAt: monthsAgo(2),
    updatedAt: monthsAgo(1)
  },

  // COURSE #10 - Cybersecurity Basics (learner5)
  {
    user: SEED_IDS.learner5,
    legalNameSnapshot: 'Sneha Reddy',
    certificateName: 'Sneha Reddy',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 94,
    autoApproved: true,
    title: 'Cybersecurity Fundamentals',
    issuer: 'Coursera - University of Maryland',
    issueDate: monthsAgo(5),
    type: 'certificate',
    credentialId: 'COURSERA-CS-2024-010',
    totalHours: 70,
    nsqfLevel: 6,
    skills: ['Cybersecurity', 'Network Security', 'Cryptography', 'Ethical Hacking', 'Risk Management'],
    description: 'Introduction to cybersecurity covering network security, cryptography, and ethical hacking principles.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'cybersecurity-cert.pdf',
      fileType: 'application/pdf',
      uploadedAt: monthsAgo(5),
    },
    sourceUrl: 'https://www.coursera.org/account/accomplishments/certificate/CS-2024-010',
    sourceDomain: 'coursera.org',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(4),
    meta: {
      platform: 'Coursera',
      category: 'Technology',
    },
    createdAt: monthsAgo(5),
    updatedAt: monthsAgo(4)
  },

  // COURSE #11 - Google Cloud Professional (learner6)
  {
    user: SEED_IDS.learner6,
    legalNameSnapshot: 'Arjun Mehta',
    certificateName: 'Arjun Mehta',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 96,
    autoApproved: true,
    title: 'Google Cloud Professional Cloud Architect',
    issuer: 'Google Cloud',
    issueDate: monthsAgo(3),
    type: 'certificate',
    credentialId: 'GCP-PCA-2024-011',
    totalHours: 90,
    nsqfLevel: 7,
    skills: ['Google Cloud', 'GCP', 'Kubernetes', 'Cloud Architecture', 'DevOps', 'Terraform'],
    description: 'Professional certification for designing and managing Google Cloud solutions.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'gcp-architect-cert.pdf',
      fileType: 'application/pdf',
      uploadedAt: monthsAgo(3),
    },
    sourceUrl: 'https://cloud.google.com/certification/cloud-architect',
    sourceDomain: 'cloud.google.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(2),
    meta: {
      platform: 'Google Cloud',
      category: 'Cloud Computing',
      expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 2)),
    },
    createdAt: monthsAgo(3),
    updatedAt: monthsAgo(2)
  },

  // COURSE #12 - Data Analytics (learner7)
  {
    user: SEED_IDS.learner7,
    legalNameSnapshot: 'Kavya Iyer',
    certificateName: 'Kavya Iyer',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 95,
    autoApproved: true,
    title: 'Google Data Analytics Professional Certificate',
    issuer: 'Coursera - Google',
    issueDate: monthsAgo(6),
    type: 'certificate',
    credentialId: 'COURSERA-GDA-2024-012',
    totalHours: 180,
    nsqfLevel: 6,
    skills: ['Data Analytics', 'SQL', 'Tableau', 'R Programming', 'Data Visualization', 'Spreadsheets'],
    description: 'Comprehensive data analytics program covering data cleaning, analysis, visualization, and storytelling.',
    file: {
      url: DEMO_CERT_IMAGE,
      fileName: 'google-data-analytics.jpg',
      fileType: 'image/jpeg',
      uploadedAt: monthsAgo(6),
    },
    sourceUrl: 'https://www.coursera.org/account/accomplishments/professional-cert/GDA-2024-012',
    sourceDomain: 'coursera.org',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(5),
    meta: {
      platform: 'Coursera',
      category: 'Data Science',
      courseCount: 8,
    },
    createdAt: monthsAgo(6),
    updatedAt: monthsAgo(5)
  },

  // ============================================
  // DUPLICATE THE 10 COURSES FOR OTHER LEARNERS (learner2-learner7)
  // ============================================

  // learner2 - React Advanced Concepts
  {
    user: SEED_IDS.learner2,
    legalNameSnapshot: 'Rahul Kumar',
    certificateName: 'Rahul Kumar',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 96,
    autoApproved: true,
    title: 'Advanced React: Hooks, Context, and Performance',
    issuer: 'Udemy',
    issueDate: monthsAgo(4),
    type: 'certificate',
    credentialId: 'UC-REACT-ADV-2024-L2-101',
    totalHours: 45,
    nsqfLevel: 6,
    skills: ['React', 'React Hooks', 'Context API', 'Performance Optimization', 'Redux'],
    description: 'Advanced React course covering hooks, context, performance optimization, and state management patterns.',
    file: { url: DEMO_CERT_IMAGE, fileName: 'react-advanced-cert.pdf', fileType: 'application/pdf', uploadedAt: monthsAgo(4) },
    sourceUrl: 'https://www.udemy.com/certificate/UC-REACT-ADV-2024-L2-101/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(3),
    meta: { platform: 'Udemy', category: 'Web Development', rating: 4.8 },
    createdAt: monthsAgo(4),
    updatedAt: monthsAgo(3)
  },

  // learner3 - React Advanced Concepts
  {
    user: SEED_IDS.learner3,
    legalNameSnapshot: 'Ananya Patel',
    certificateName: 'Ananya Patel',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 96,
    autoApproved: true,
    title: 'Advanced React: Hooks, Context, and Performance',
    issuer: 'Udemy',
    issueDate: monthsAgo(4),
    type: 'certificate',
    credentialId: 'UC-REACT-ADV-2024-L3-101',
    totalHours: 45,
    nsqfLevel: 6,
    skills: ['React', 'React Hooks', 'Context API', 'Performance Optimization', 'Redux'],
    description: 'Advanced React course covering hooks, context, performance optimization, and state management patterns.',
    file: { url: DEMO_CERT_IMAGE, fileName: 'react-advanced-cert.pdf', fileType: 'application/pdf', uploadedAt: monthsAgo(4) },
    sourceUrl: 'https://www.udemy.com/certificate/UC-REACT-ADV-2024-L3-101/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(3),
    meta: { platform: 'Udemy', category: 'Web Development', rating: 4.8 },
    createdAt: monthsAgo(4),
    updatedAt: monthsAgo(3)
  },

  // learner4 - React Advanced Concepts
  {
    user: SEED_IDS.learner4,
    legalNameSnapshot: 'Vikram Singh',
    certificateName: 'Vikram Singh',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 96,
    autoApproved: true,
    title: 'Advanced React: Hooks, Context, and Performance',
    issuer: 'Udemy',
    issueDate: monthsAgo(4),
    type: 'certificate',
    credentialId: 'UC-REACT-ADV-2024-L4-101',
    totalHours: 45,
    nsqfLevel: 6,
    skills: ['React', 'React Hooks', 'Context API', 'Performance Optimization', 'Redux'],
    description: 'Advanced React course covering hooks, context, performance optimization, and state management patterns.',
    file: { url: DEMO_CERT_IMAGE, fileName: 'react-advanced-cert.pdf', fileType: 'application/pdf', uploadedAt: monthsAgo(4) },
    sourceUrl: 'https://www.udemy.com/certificate/UC-REACT-ADV-2024-L4-101/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(3),
    meta: { platform: 'Udemy', category: 'Web Development', rating: 4.8 },
    createdAt: monthsAgo(4),
    updatedAt: monthsAgo(3)
  },

  // learner5 - React Advanced Concepts
  {
    user: SEED_IDS.learner5,
    legalNameSnapshot: 'Sneha Reddy',
    certificateName: 'Sneha Reddy',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 96,
    autoApproved: true,
    title: 'Advanced React: Hooks, Context, and Performance',
    issuer: 'Udemy',
    issueDate: monthsAgo(4),
    type: 'certificate',
    credentialId: 'UC-REACT-ADV-2024-L5-101',
    totalHours: 45,
    nsqfLevel: 6,
    skills: ['React', 'React Hooks', 'Context API', 'Performance Optimization', 'Redux'],
    description: 'Advanced React course covering hooks, context, performance optimization, and state management patterns.',
    file: { url: DEMO_CERT_IMAGE, fileName: 'react-advanced-cert.pdf', fileType: 'application/pdf', uploadedAt: monthsAgo(4) },
    sourceUrl: 'https://www.udemy.com/certificate/UC-REACT-ADV-2024-L5-101/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(3),
    meta: { platform: 'Udemy', category: 'Web Development', rating: 4.8 },
    createdAt: monthsAgo(4),
    updatedAt: monthsAgo(3)
  },

  // learner6 - React Advanced Concepts
  {
    user: SEED_IDS.learner6,
    legalNameSnapshot: 'Arjun Mehta',
    certificateName: 'Arjun Mehta',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 96,
    autoApproved: true,
    title: 'Advanced React: Hooks, Context, and Performance',
    issuer: 'Udemy',
    issueDate: monthsAgo(4),
    type: 'certificate',
    credentialId: 'UC-REACT-ADV-2024-L6-101',
    totalHours: 45,
    nsqfLevel: 6,
    skills: ['React', 'React Hooks', 'Context API', 'Performance Optimization', 'Redux'],
    description: 'Advanced React course covering hooks, context, performance optimization, and state management patterns.',
    file: { url: DEMO_CERT_IMAGE, fileName: 'react-advanced-cert.pdf', fileType: 'application/pdf', uploadedAt: monthsAgo(4) },
    sourceUrl: 'https://www.udemy.com/certificate/UC-REACT-ADV-2024-L6-101/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(3),
    meta: { platform: 'Udemy', category: 'Web Development', rating: 4.8 },
    createdAt: monthsAgo(4),
    updatedAt: monthsAgo(3)
  },

  // learner7 - React Advanced Concepts
  {
    user: SEED_IDS.learner7,
    legalNameSnapshot: 'Kavya Iyer',
    certificateName: 'Kavya Iyer',
    nameMatchConfidence: 100,
    verificationStatus: 'VERIFIED',
    finalVerificationScore: 96,
    autoApproved: true,
    title: 'Advanced React: Hooks, Context, and Performance',
    issuer: 'Udemy',
    issueDate: monthsAgo(4),
    type: 'certificate',
    credentialId: 'UC-REACT-ADV-2024-L7-101',
    totalHours: 45,
    nsqfLevel: 6,
    skills: ['React', 'React Hooks', 'Context API', 'Performance Optimization', 'Redux'],
    description: 'Advanced React course covering hooks, context, performance optimization, and state management patterns.',
    file: { url: DEMO_CERT_IMAGE, fileName: 'react-advanced-cert.pdf', fileType: 'application/pdf', uploadedAt: monthsAgo(4) },
    sourceUrl: 'https://www.udemy.com/certificate/UC-REACT-ADV-2024-L7-101/',
    sourceDomain: 'udemy.com',
    isDomainTrusted: true,
    isIssuerVerified: true,
    isPublic: true,
    status: 'verified',
    verifiedAt: monthsAgo(3),
    meta: { platform: 'Udemy', category: 'Web Development', rating: 4.8 },
    createdAt: monthsAgo(4),
    updatedAt: monthsAgo(3)
  },
];

const seedCredentials = async () => {
  const createdCredentials = await Credential.insertMany(credentials);
  console.log(`✅ Credentials created: ${createdCredentials.length} (including demo courses)`);
  return createdCredentials;
};

export default seedCredentials;
