import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import User from '../features-old/user/models/user.model.js';

// Predefined IDs for reference in other seed files
export const SEED_IDS = {
  // Learners (10 users) - Demo: learner1 (Priya)
  learner1: new mongoose.Types.ObjectId('507f1f77bcf86cd799439011'),
  learner2: new mongoose.Types.ObjectId('507f1f77bcf86cd799439012'),
  learner3: new mongoose.Types.ObjectId('507f1f77bcf86cd799439013'),
  learner4: new mongoose.Types.ObjectId('507f1f77bcf86cd799439014'),
  learner5: new mongoose.Types.ObjectId('507f1f77bcf86cd799439015'),
  learner6: new mongoose.Types.ObjectId('507f1f77bcf86cd799439016'),
  learner7: new mongoose.Types.ObjectId('507f1f77bcf86cd799439017'),
  learner8: new mongoose.Types.ObjectId('507f1f77bcf86cd799439018'),
  learner9: new mongoose.Types.ObjectId('507f1f77bcf86cd799439019'),
  learner10: new mongoose.Types.ObjectId('507f1f77bcf86cd799439020'),

  // Regulators (10 users) - Demo: regulator1 (Dr. Kavita)
  regulator1: new mongoose.Types.ObjectId('507f1f77bcf86cd799439031'),
  regulator2: new mongoose.Types.ObjectId('507f1f77bcf86cd799439032'),
  regulator3: new mongoose.Types.ObjectId('507f1f77bcf86cd799439033'),
  regulator4: new mongoose.Types.ObjectId('507f1f77bcf86cd799439034'),
  regulator5: new mongoose.Types.ObjectId('507f1f77bcf86cd799439035'),
  regulator6: new mongoose.Types.ObjectId('507f1f77bcf86cd799439036'),
  regulator7: new mongoose.Types.ObjectId('507f1f77bcf86cd799439037'),
  regulator8: new mongoose.Types.ObjectId('507f1f77bcf86cd799439038'),
  regulator9: new mongoose.Types.ObjectId('507f1f77bcf86cd799439039'),
  regulator10: new mongoose.Types.ObjectId('507f1f77bcf86cd799439040'),

  // Additional regulators for DigiLocker institutions
  regulator11: new mongoose.Types.ObjectId('507f1f77bcf86cd799439051'),
  regulator12: new mongoose.Types.ObjectId('507f1f77bcf86cd799439052'),
  regulator13: new mongoose.Types.ObjectId('507f1f77bcf86cd799439053'),
  regulator14: new mongoose.Types.ObjectId('507f1f77bcf86cd799439054'),
  regulator15: new mongoose.Types.ObjectId('507f1f77bcf86cd799439055'),
  regulator16: new mongoose.Types.ObjectId('507f1f77bcf86cd799439056'),
  regulator17: new mongoose.Types.ObjectId('507f1f77bcf86cd799439057'),

  // Employers (10 users) - Demo: employer1 (Meera)
  employer1: new mongoose.Types.ObjectId('507f1f77bcf86cd799439041'),
  employer2: new mongoose.Types.ObjectId('507f1f77bcf86cd799439042'),
  employer3: new mongoose.Types.ObjectId('507f1f77bcf86cd799439043'),
  employer4: new mongoose.Types.ObjectId('507f1f77bcf86cd799439044'),
  employer5: new mongoose.Types.ObjectId('507f1f77bcf86cd799439045'),
  employer6: new mongoose.Types.ObjectId('507f1f77bcf86cd799439046'),
  employer7: new mongoose.Types.ObjectId('507f1f77bcf86cd799439047'),
  employer8: new mongoose.Types.ObjectId('507f1f77bcf86cd799439048'),
  employer9: new mongoose.Types.ObjectId('507f1f77bcf86cd799439049'),
  employer10: new mongoose.Types.ObjectId('507f1f77bcf86cd799439050'),
};

// ==================== CREDENTIALISTS (10 users) ====================
const learners = [
  // DEMO USER 1: Priya Sharma
  {
    _id: SEED_IDS.learner1,
    username: 'priya_sharma',
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    password: 'password123',
    role: 'learner',
    avatar: 'https://i.pravatar.cc/150?img=5',
    bio: 'Full-stack developer with 5+ years of experience in MERN stack. Passionate about building scalable web applications and mentoring junior developers.',
    phoneNo: '+91-9876543210',
    skills: [
      'JavaScript',
      'React',
      'Node.js',
      'MongoDB',
      'Express',
      'TypeScript',
      'AWS',
      'Docker',
    ],
    education: [
      {
        institution: 'IIT Delhi',
        degree: 'Bachelor of Technology',
        fieldOfStudy: 'Computer Science',
        startYear: 2015,
        endYear: 2019,
        current: false,
      },
    ],
    experience: [
      {
        company: 'Tech Solutions Pvt Ltd',
        position: 'Senior Full Stack Developer',
        startDate: new Date('2020-01-01'),
        current: true,
        description:
          'Leading development of enterprise applications using MERN stack.',
      },
    ],
    achievements: [
      {
        title: 'Best Developer Award 2023',
        issuer: 'Tech Solutions',
        date: new Date('2023-12-01'),
        description: 'Recognized for outstanding contribution to projects.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/priyasharma',
      github: 'https://github.com/priyasharma-dev',
      portfolio: 'https://priyasharma.dev',
      twitter: 'https://twitter.com/priya_dev',
    },
    isPublic: true,
  },
  {
    _id: SEED_IDS.learner2,
    username: 'ananya_desai',
    name: 'Ananya Desai',
    email: 'ananya.desai@example.com',
    password: 'password123',
    role: 'learner',
    avatar: 'https://i.pravatar.cc/150?img=9',
    bio: 'Data scientist specializing in machine learning and AI. Passionate about leveraging data to solve complex business problems and drive innovation.',
    phoneNo: '+91-9876543211',
    skills: [
      'Python',
      'Machine Learning',
      'TensorFlow',
      'PyTorch',
      'Data Analysis',
      'Pandas',
      'NumPy',
      'Scikit-learn',
      'Deep Learning',
      'NLP',
    ],
    education: [
      {
        institution: 'BITS Pilani',
        degree: 'M.Tech',
        fieldOfStudy: 'Data Science',
        startYear: 2018,
        endYear: 2020,
        current: false,
      },
      {
        institution: 'Mumbai University',
        degree: 'B.Tech',
        fieldOfStudy: 'Computer Engineering',
        startYear: 2014,
        endYear: 2018,
        current: false,
      },
    ],
    experience: [
      {
        company: 'DataTech Analytics',
        position: 'Senior Data Scientist',
        startDate: new Date('2022-03-01'),
        current: true,
        description:
          'Leading ML projects for predictive analytics and recommendation systems. Built models improving customer retention by 25%.',
      },
      {
        company: 'AI Innovations Pvt Ltd',
        position: 'Data Scientist',
        startDate: new Date('2020-06-01'),
        endDate: new Date('2022-02-28'),
        current: false,
        description:
          'Developed ML models for business intelligence and automated data pipelines.',
      },
    ],
    achievements: [
      {
        title: 'Best ML Project Award 2023',
        issuer: 'DataTech Analytics',
        date: new Date('2023-08-15'),
        description:
          'Recognized for developing innovative predictive analytics model.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/ananya-desai',
      github: 'https://github.com/ananya-ds',
      portfolio: 'https://ananya-desai.dev',
    },
    isPublic: true,
  },
  {
    _id: SEED_IDS.learner3,
    username: 'neha_gupta',
    name: 'Neha Gupta',
    email: 'neha.gupta@example.com',
    password: 'password123',
    role: 'learner',
    avatar: 'https://i.pravatar.cc/150?img=47',
    bio: 'Mobile app developer with expertise in React Native and Flutter. Published 15+ apps with 500K+ downloads on App Store and Play Store.',
    phoneNo: '+91-9876543212',
    skills: [
      'React Native',
      'Flutter',
      'iOS',
      'Android',
      'Firebase',
      'Redux',
      'GraphQL',
      'REST APIs',
      'Mobile UI/UX',
      'CI/CD',
    ],
    education: [
      {
        institution: 'Anna University',
        degree: 'B.E',
        fieldOfStudy: 'Computer Science',
        startYear: 2016,
        endYear: 2020,
        current: false,
      },
    ],
    experience: [
      {
        company: 'MobileFirst Tech',
        position: 'Senior Mobile Developer',
        startDate: new Date('2022-05-01'),
        current: true,
        description:
          'Leading mobile development team. Built flagship app with 200K+ active users.',
      },
      {
        company: 'AppCraft Solutions',
        position: 'Mobile Developer',
        startDate: new Date('2020-08-01'),
        endDate: new Date('2022-04-30'),
        current: false,
        description:
          'Developed cross-platform mobile applications for various clients.',
      },
    ],
    achievements: [
      {
        title: 'App of the Month Award',
        issuer: 'MobileFirst Tech',
        date: new Date('2023-06-01'),
        description: 'Developed highest rated customer app of 2023.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/neha-gupta-mobile',
      github: 'https://github.com/neha-mobile-dev',
      portfolio: 'https://nehagupta.dev',
    },
    isPublic: true,
  },
  {
    _id: SEED_IDS.learner4,
    username: 'divya_iyer',
    name: 'Divya Iyer',
    email: 'divya.iyer@example.com',
    password: 'password123',
    role: 'learner',
    avatar: 'https://i.pravatar.cc/150?img=25',
    bio: 'UI/UX designer creating beautiful digital experiences. Specialized in user-centered design with focus on accessibility and inclusivity.',
    phoneNo: '+91-9876543213',
    skills: [
      'Figma',
      'Adobe XD',
      'UI Design',
      'UX Research',
      'Prototyping',
      'Sketch',
      'User Testing',
      'Wireframing',
      'Design Systems',
      'Adobe Creative Suite',
    ],
    education: [
      {
        institution: 'NID Ahmedabad',
        degree: 'Bachelor of Design',
        fieldOfStudy: 'Interaction Design',
        startYear: 2016,
        endYear: 2020,
        current: false,
      },
    ],
    experience: [
      {
        company: 'DesignCraft Studio',
        position: 'Senior UI/UX Designer',
        startDate: new Date('2023-01-01'),
        current: true,
        description:
          'Leading design team and managing end-to-end design process for multiple products.',
      },
      {
        company: 'CreativeHub Agency',
        position: 'UI/UX Designer',
        startDate: new Date('2020-07-01'),
        endDate: new Date('2022-12-31'),
        current: false,
        description:
          'Designed user interfaces for web and mobile applications for various clients.',
      },
    ],
    achievements: [
      {
        title: 'Best Design Portfolio 2023',
        issuer: 'Design Awards India',
        date: new Date('2023-10-20'),
        description: 'Recognized for innovative and user-centric design work.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/divya-iyer-design',
      behance: 'https://behance.net/divyaiyer',
      portfolio: 'https://divyaiyer.design',
    },
    isPublic: true,
  },
  {
    _id: SEED_IDS.learner5,
    username: 'sneha_kulkarni',
    name: 'Sneha Kulkarni',
    email: 'sneha.kulkarni@example.com',
    password: 'password123',
    role: 'learner',
    avatar: 'https://i.pravatar.cc/150?img=38',
    bio: 'Backend engineer specializing in Python and Django. Expert in building high-performance RESTful APIs and microservices architecture.',
    phoneNo: '+91-9876543214',
    skills: [
      'Python',
      'Django',
      'PostgreSQL',
      'Redis',
      'Docker',
      'FastAPI',
      'Celery',
      'REST APIs',
      'GraphQL',
      'Microservices',
    ],
    education: [
      {
        institution: 'Pune University',
        degree: 'B.Tech',
        fieldOfStudy: 'Information Technology',
        startYear: 2015,
        endYear: 2019,
        current: false,
      },
    ],
    experience: [
      {
        company: 'WebServices Inc',
        position: 'Senior Backend Developer',
        startDate: new Date('2021-10-01'),
        current: true,
        description:
          'Architecting and building scalable backend systems handling 10M+ requests daily.',
      },
      {
        company: 'TechStart Solutions',
        position: 'Backend Developer',
        startDate: new Date('2019-09-01'),
        endDate: new Date('2021-09-30'),
        current: false,
        description:
          'Developed backend services and APIs for web applications.',
      },
    ],
    achievements: [
      {
        title: 'Performance Optimization Award',
        issuer: 'WebServices Inc',
        date: new Date('2023-04-15'),
        description: 'Improved API response time by 60% through optimization.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/sneha-kulkarni-dev',
      github: 'https://github.com/sneha-backend',
    },
    isPublic: false,
  },
  {
    _id: SEED_IDS.learner6,
    username: 'riya_patel',
    name: 'Riya Patel',
    email: 'riya.patel@example.com',
    password: 'password123',
    role: 'learner',
    avatar: 'https://i.pravatar.cc/150?img=31',
    bio: 'DevOps engineer with focus on CI/CD and cloud infrastructure. AWS certified solutions architect with expertise in container orchestration.',
    phoneNo: '+91-9876543215',
    skills: [
      'AWS',
      'Kubernetes',
      'Terraform',
      'Jenkins',
      'Linux',
      'Docker',
      'GitLab CI',
      'Ansible',
      'Prometheus',
      'Grafana',
    ],
    education: [
      {
        institution: 'VIT Vellore',
        degree: 'B.Tech',
        fieldOfStudy: 'Computer Science',
        startYear: 2015,
        endYear: 2019,
        current: false,
      },
    ],
    experience: [
      {
        company: 'CloudOps Solutions',
        position: 'Senior DevOps Engineer',
        startDate: new Date('2022-01-01'),
        current: true,
        description:
          'Leading DevOps team managing multi-cloud infrastructure for 50+ microservices.',
      },
      {
        company: 'TechInfra Pvt Ltd',
        position: 'DevOps Engineer',
        startDate: new Date('2019-07-01'),
        endDate: new Date('2021-12-31'),
        current: false,
        description:
          'Implemented CI/CD pipelines and managed AWS infrastructure.',
      },
    ],
    achievements: [
      {
        title: 'AWS Certified Solutions Architect',
        issuer: 'Amazon Web Services',
        date: new Date('2022-05-10'),
        description: 'Professional level certification for cloud architecture.',
      },
      {
        title: 'Infrastructure Excellence Award',
        issuer: 'CloudOps Solutions',
        date: new Date('2023-09-01'),
        description:
          'Reduced infrastructure costs by 40% through optimization.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/riya-patel-devops',
      github: 'https://github.com/riya-cloudops',
    },
    isPublic: true,
  },
  {
    _id: SEED_IDS.learner7,
    username: 'kavya_reddy',
    name: 'Kavya Reddy',
    email: 'kavya.reddy@example.com',
    password: 'password123',
    role: 'learner',
    avatar: 'https://i.pravatar.cc/150?img=27',
    bio: 'QA engineer ensuring software quality through automation. Specialized in end-to-end testing and continuous quality assurance.',
    phoneNo: '+91-9876543216',
    skills: [
      'Selenium',
      'Cypress',
      'Jest',
      'API Testing',
      'Automation',
      'Postman',
      'JMeter',
      'TestNG',
      'Cucumber',
      'Performance Testing',
    ],
    education: [
      {
        institution: 'JNTU Hyderabad',
        degree: 'B.Tech',
        fieldOfStudy: 'Computer Science',
        startYear: 2016,
        endYear: 2020,
        current: false,
      },
    ],
    experience: [
      {
        company: 'QualityTech',
        position: 'Senior QA Engineer',
        startDate: new Date('2022-08-01'),
        current: true,
        description:
          'Leading QA team and implementing comprehensive test automation frameworks. Reduced testing time by 70%.',
      },
      {
        company: 'TestPro Solutions',
        position: 'QA Engineer',
        startDate: new Date('2020-08-01'),
        endDate: new Date('2022-07-31'),
        current: false,
        description:
          'Developed automated test suites for web and mobile applications.',
      },
    ],
    achievements: [
      {
        title: 'Quality Champion 2023',
        issuer: 'QualityTech',
        date: new Date('2023-11-10'),
        description: 'Achieved 99.5% test coverage across all projects.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/kavya-reddy-qa',
      github: 'https://github.com/kavya-qa',
    },
    isPublic: true,
  },
  {
    _id: SEED_IDS.learner8,
    username: 'pooja_menon',
    name: 'Pooja Menon',
    email: 'pooja.menon@example.com',
    password: 'password123',
    role: 'learner',
    avatar: 'https://i.pravatar.cc/150?img=41',
    bio: 'Frontend developer with passion for creating responsive UIs. Expert in modern JavaScript frameworks and performance optimization.',
    phoneNo: '+91-9876543217',
    skills: [
      'React',
      'Vue.js',
      'JavaScript',
      'CSS',
      'HTML',
      'TypeScript',
      'Next.js',
      'Tailwind CSS',
      'Webpack',
      'Redux',
    ],
    education: [
      {
        institution: 'Delhi University',
        degree: 'BCA',
        fieldOfStudy: 'Computer Applications',
        startYear: 2017,
        endYear: 2020,
        current: false,
      },
    ],
    experience: [
      {
        company: 'WebCraft Agency',
        position: 'Senior Frontend Developer',
        startDate: new Date('2022-06-01'),
        current: true,
        description:
          'Building modern, accessible web interfaces. Leading frontend architecture decisions.',
      },
      {
        company: 'DigitalWeb Studios',
        position: 'Frontend Developer',
        startDate: new Date('2020-06-01'),
        endDate: new Date('2022-05-31'),
        current: false,
        description:
          'Developed responsive web applications using React and Vue.js.',
      },
    ],
    achievements: [
      {
        title: 'Best Frontend Implementation 2023',
        issuer: 'WebCraft Agency',
        date: new Date('2023-07-20'),
        description:
          'Built award-winning e-commerce platform with exceptional UX.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/pooja-menon-frontend',
      github: 'https://github.com/pooja-frontend',
      portfolio: 'https://poojamenon.dev',
    },
    isPublic: true,
  },
  {
    _id: SEED_IDS.learner9,
    username: 'aishwarya_singh',
    name: 'Aishwarya Singh',
    email: 'aishwarya.singh@example.com',
    password: 'password123',
    role: 'learner',
    avatar: 'https://i.pravatar.cc/150?img=42',
    bio: 'Blockchain developer working on Web3 technologies. Pioneering DeFi solutions and smart contract security.',
    phoneNo: '+91-9876543218',
    skills: [
      'Solidity',
      'Ethereum',
      'Web3.js',
      'Smart Contracts',
      'Hardhat',
      'Truffle',
      'IPFS',
      'DeFi',
      'NFTs',
      'Rust',
    ],
    education: [
      {
        institution: 'IIT Bombay',
        degree: 'B.Tech',
        fieldOfStudy: 'Computer Science',
        startYear: 2016,
        endYear: 2020,
        current: false,
      },
    ],
    experience: [
      {
        company: 'BlockTech Innovations',
        position: 'Lead Blockchain Developer',
        startDate: new Date('2023-01-01'),
        current: true,
        description:
          'Leading blockchain development team. Built multiple DeFi protocols handling $50M+ in TVL.',
      },
      {
        company: 'CryptoStart Labs',
        position: 'Blockchain Developer',
        startDate: new Date('2020-09-01'),
        endDate: new Date('2022-12-31'),
        current: false,
        description:
          'Developed smart contracts and decentralized applications on Ethereum.',
      },
    ],
    achievements: [
      {
        title: 'Best DeFi Project 2023',
        issuer: 'Web3 Conference India',
        date: new Date('2023-05-25'),
        description:
          'Built innovative yield farming protocol with advanced security features.',
      },
      {
        title: 'Ethereum Foundation Grant',
        issuer: 'Ethereum Foundation',
        date: new Date('2022-09-15'),
        description:
          'Received grant for open-source blockchain tools development.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/aishwarya-blockchain',
      github: 'https://github.com/aishwarya-web3',
      twitter: 'https://twitter.com/aishwarya_web3',
    },
    isPublic: true,
  },
  {
    _id: SEED_IDS.learner10,
    username: 'shreya_nair',
    name: 'Shreya Nair',
    email: 'shreya.nair@example.com',
    password: 'password123',
    role: 'learner',
    avatar: 'https://i.pravatar.cc/150?img=36',
    bio: 'Cloud solutions architect specializing in AWS and Azure. Expert in designing scalable, cost-effective cloud infrastructure.',
    phoneNo: '+91-9876543219',
    skills: [
      'AWS',
      'Azure',
      'Cloud Architecture',
      'Microservices',
      'Lambda',
      'S3',
      'EC2',
      'Cloud Security',
      'Cost Optimization',
      'Multi-Cloud',
    ],
    education: [
      {
        institution: 'BITS Pilani',
        degree: 'B.E',
        fieldOfStudy: 'Electronics and Communication',
        startYear: 2015,
        endYear: 2019,
        current: false,
      },
      {
        institution: 'IIM Bangalore',
        degree: 'Executive MBA',
        fieldOfStudy: 'Technology Management',
        startYear: 2021,
        endYear: 2023,
        current: false,
      },
    ],
    experience: [
      {
        company: 'CloudScale Solutions',
        position: 'Principal Cloud Architect',
        startDate: new Date('2022-04-01'),
        current: true,
        description:
          'Leading cloud transformation projects for Fortune 500 companies. Designed infrastructure serving 100M+ users.',
      },
      {
        company: 'TechCloud Services',
        position: 'Cloud Architect',
        startDate: new Date('2019-08-01'),
        endDate: new Date('2022-03-31'),
        current: false,
        description:
          'Architected cloud solutions for enterprise clients across various industries.',
      },
    ],
    achievements: [
      {
        title: 'AWS Certified Solutions Architect Professional',
        issuer: 'Amazon Web Services',
        date: new Date('2021-03-10'),
        description: 'Advanced certification for cloud architecture expertise.',
      },
      {
        title: 'Cloud Innovation Award',
        issuer: 'CloudScale Solutions',
        date: new Date('2023-08-15'),
        description:
          'Reduced cloud costs by 45% for major client through optimization.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/shreya-nair-cloud',
      twitter: 'https://twitter.com/shreya_cloud',
      website: 'https://shreyanair.tech',
    },
    isPublic: true,
  },
];

// ==================== VALIDANTS (10 users) ====================
const regulators = [
  // DEMO USER 2: Dr. Kavita Rao
  {
    _id: SEED_IDS.regulator1,
    username: 'dr_kavita_rao',
    name: 'Dr. Kavita Rao',
    email: 'kavita.rao@credverify.com',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=47',
    bio: 'Senior credential verifier with 8+ years of experience in educational and professional certification validation.',
    phoneNo: '+91-11-4567-8901',
    skills: [
      'Credential Verification',
      'Document Authentication',
      'Academic Assessment',
      'Compliance Review',
      'Data Analysis',
    ],
    education: [
      {
        institution: 'University of Delhi',
        degree: 'Ph.D.',
        fieldOfStudy: 'Education Administration',
        startYear: 2010,
        endYear: 2014,
        current: false,
      },
      {
        institution: 'Lady Shri Ram College',
        degree: 'Master of Arts',
        fieldOfStudy: 'Education',
        startYear: 2008,
        endYear: 2010,
        current: false,
      },
    ],
    experience: [
      {
        company: 'CredVerify Central Authority',
        position: 'Senior Credential Verifier',
        startDate: new Date('2017-05-01'),
        current: true,
        description:
          'Leading the technology credentials verification division. Verified 500+ credentials with 99.8% accuracy.',
      },
      {
        company: 'National Skill Development Corporation',
        position: 'Verification Officer',
        startDate: new Date('2014-07-01'),
        endDate: new Date('2017-04-30'),
        current: false,
        description:
          'Verified professional certifications and skill credentials across various industries.',
      },
    ],
    achievements: [
      {
        title: 'Excellence in Verification Award 2023',
        issuer: 'CredVerify Central Authority',
        date: new Date('2023-11-15'),
        description:
          'Recognized for maintaining highest accuracy and efficiency standards.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/drkavitarao',
    },
    // Regulator-specific fields
    institution: 'CredVerify Central Authority',
    verificationAuthorityId: 'CVCA-001',
    department: 'Technology Credentials Division',
    contactPhone: '+91-11-4567-8901',
    contactEmail: 'kavita.rao@credverify.com',
    officeLocation: 'Building A, Floor 3',
    verifiedCount: 2,
    rejectedCount: 1,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator2,
    username: 'prof_meera_krishnan',
    name: 'Prof. Meera Krishnan',
    email: 'meera.krishnan@nit.edu',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=28',
    bio: 'Professor specializing in IT education and credential verification.',
    phoneNo: '+91-824-247-3456',
    skills: [
      'Academic Verification',
      'IT Education',
      'Credential Assessment',
      'Research Evaluation',
    ],
    education: [
      {
        institution: 'Indian Institute of Science',
        degree: 'Ph.D.',
        fieldOfStudy: 'Computer Science',
        startYear: 2005,
        endYear: 2010,
        current: false,
      },
    ],
    experience: [
      {
        company: 'National Institute of Technology Karnataka',
        position: 'Professor',
        startDate: new Date('2015-06-01'),
        current: true,
        description: 'Teaching and credential verification for IT department.',
      },
    ],
    achievements: [],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/profmeerakrishnan',
    },
    // Regulator-specific fields
    institution: 'National Institute of Technology Karnataka',
    verificationAuthorityId: 'NITK-VER-045',
    department: 'Information Technology',
    contactPhone: '+91-824-247-3456',
    contactEmail: 'meera.krishnan@nit.edu',
    officeLocation: 'IT Block, Room 204',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator3,
    username: 'dr_priya_malhotra',
    name: 'Dr. Priya Malhotra',
    email: 'priya.malhotra@du.ac.in',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=32',
    bio: 'Senior faculty member handling credential verification for technology programs. Specialized in academic integrity and credential authentication.',
    phoneNo: '+91-11-2766-7890',
    skills: [
      'Academic Verification',
      'Credential Assessment',
      'Educational Standards',
      'Document Authentication',
      'Compliance Review',
    ],
    education: [
      {
        institution: 'University of Delhi',
        degree: 'Ph.D.',
        fieldOfStudy: 'Computer Science Education',
        startYear: 2008,
        endYear: 2013,
        current: false,
      },
      {
        institution: 'Miranda House, Delhi University',
        degree: 'M.Sc',
        fieldOfStudy: 'Computer Science',
        startYear: 2006,
        endYear: 2008,
        current: false,
      },
    ],
    experience: [
      {
        company: 'University of Delhi',
        position: 'Associate Professor & Credential Verifier',
        startDate: new Date('2015-07-01'),
        current: true,
        description:
          'Teaching computer applications and managing credential verification for the department.',
      },
      {
        company: 'Ramjas College, DU',
        position: 'Assistant Professor',
        startDate: new Date('2013-08-01'),
        endDate: new Date('2015-06-30'),
        current: false,
        description:
          'Taught computer science courses and assisted in academic verification.',
      },
    ],
    achievements: [
      {
        title: 'Excellence in Academic Verification',
        issuer: 'University of Delhi',
        date: new Date('2023-03-15'),
        description:
          'Recognized for maintaining high standards in credential verification.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/drpriyamalhotra',
    },
    institution: 'University of Delhi',
    verificationAuthorityId: 'DU-VER-134',
    department: 'Computer Applications',
    contactPhone: '+91-11-2766-7890',
    contactEmail: 'priya.malhotra@du.ac.in',
    officeLocation: 'North Campus, Room 301',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator4,
    username: 'prof_anjali_bose',
    name: 'Prof. Anjali Bose',
    email: 'anjali.bose@jnu.ac.in',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=45',
    bio: 'Associate Professor specializing in computer science education and credential verification for graduate programs.',
    phoneNo: '+91-11-2670-4567',
    skills: [
      'Graduate Credential Assessment',
      'Research Validation',
      'Academic Standards',
      'CS Education',
      'Thesis Evaluation',
    ],
    education: [
      {
        institution: 'IIT Delhi',
        degree: 'Ph.D.',
        fieldOfStudy: 'Computer Science',
        startYear: 2005,
        endYear: 2010,
        current: false,
      },
      {
        institution: 'Jadavpur University',
        degree: 'M.Tech',
        fieldOfStudy: 'Computer Science and Engineering',
        startYear: 2003,
        endYear: 2005,
        current: false,
      },
    ],
    experience: [
      {
        company: 'Jawaharlal Nehru University',
        position: 'Associate Professor',
        startDate: new Date('2016-01-01'),
        current: true,
        description:
          'Teaching and research in computer science. Managing graduate credential verification.',
      },
      {
        company: 'JNU',
        position: 'Assistant Professor',
        startDate: new Date('2010-08-01'),
        endDate: new Date('2015-12-31'),
        current: false,
        description: 'Taught computer systems and programming courses.',
      },
    ],
    achievements: [],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/profanjalibose',
    },
    institution: 'Jawaharlal Nehru University',
    verificationAuthorityId: 'JNU-VER-089',
    department: 'School of Computer & Systems Sciences',
    contactPhone: '+91-11-2670-4567',
    contactEmail: 'anjali.bose@jnu.ac.in',
    officeLocation: 'SCS Building, 2nd Floor',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator5,
    username: 'dr_sneha_verma',
    name: 'Dr. Sneha Verma',
    email: 'sneha.verma@bits-pilani.ac.in',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=20',
    bio: 'Assistant Professor and credential validator for CS degrees. Focus on technology skill verification and academic assessment.',
    phoneNo: '+91-1596-242-345',
    skills: [
      'CS Credential Verification',
      'Skill Assessment',
      'Academic Evaluation',
      'Technology Education',
      'Standards Compliance',
    ],
    education: [
      {
        institution: 'IISc Bangalore',
        degree: 'Ph.D.',
        fieldOfStudy: 'Computer Science',
        startYear: 2012,
        endYear: 2017,
        current: false,
      },
      {
        institution: 'BITS Pilani',
        degree: 'M.E',
        fieldOfStudy: 'Software Systems',
        startYear: 2010,
        endYear: 2012,
        current: false,
      },
    ],
    experience: [
      {
        company: 'BITS Pilani',
        position: 'Assistant Professor',
        startDate: new Date('2017-07-01'),
        current: true,
        description:
          'Teaching CS courses and handling credential verification for the department.',
      },
    ],
    achievements: [
      {
        title: 'Best Teacher Award',
        issuer: 'BITS Pilani',
        date: new Date('2022-08-15'),
        description:
          'Recognized for excellence in teaching and mentoring students.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/drsnehaverma',
    },
    institution: 'BITS Pilani',
    verificationAuthorityId: 'BITS-VER-089',
    department: 'Computer Science',
    contactPhone: '+91-1596-242-345',
    contactEmail: 'sneha.verma@bits-pilani.ac.in',
    officeLocation: 'CS Department, Tower 2',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator6,
    username: 'prof_lakshmi_iyer',
    name: 'Prof. Lakshmi Iyer',
    email: 'lakshmi.iyer@vit.ac.in',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=35',
    bio: 'Professor with expertise in verifying engineering credentials. Over 15 years of experience in academic administration.',
    phoneNo: '+91-416-220-2345',
    skills: [
      'Engineering Credential Verification',
      'Academic Assessment',
      'Quality Assurance',
      'Accreditation',
      'Educational Standards',
    ],
    education: [
      {
        institution: 'Anna University',
        degree: 'Ph.D.',
        fieldOfStudy: 'Electronics and Communication Engineering',
        startYear: 2003,
        endYear: 2008,
        current: false,
      },
      {
        institution: 'CEG, Anna University',
        degree: 'M.E',
        fieldOfStudy: 'VLSI Design',
        startYear: 2001,
        endYear: 2003,
        current: false,
      },
    ],
    experience: [
      {
        company: 'Vellore Institute of Technology',
        position: 'Professor & Verification Head',
        startDate: new Date('2013-06-01'),
        current: true,
        description:
          'Leading credential verification division and teaching senior-level courses.',
      },
      {
        company: 'VIT',
        position: 'Associate Professor',
        startDate: new Date('2008-08-01'),
        endDate: new Date('2013-05-31'),
        current: false,
        description:
          'Taught ECE courses and assisted in academic administration.',
      },
    ],
    achievements: [],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/proflakshmiiyer',
    },
    institution: 'Vellore Institute of Technology',
    verificationAuthorityId: 'VIT-VER-112',
    department: 'Electronics and Computer Engineering',
    contactPhone: '+91-416-220-2345',
    contactEmail: 'lakshmi.iyer@vit.ac.in',
    officeLocation: 'ECE Block, Floor 5',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator7,
    username: 'dr_ritu_sharma',
    name: 'Dr. Ritu Sharma',
    email: 'ritu.sharma@iitb.ac.in',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=43',
    bio: 'Professor at IIT Bombay specializing in CS degree verification. Leading expert in academic credential authentication.',
    phoneNo: '+91-22-2576-7890',
    skills: [
      'IIT Credential Verification',
      'Academic Integrity',
      'Research Validation',
      'Quality Control',
      'Educational Policy',
    ],
    education: [
      {
        institution: 'Stanford University',
        degree: 'Ph.D.',
        fieldOfStudy: 'Computer Science',
        startYear: 2006,
        endYear: 2011,
        current: false,
      },
      {
        institution: 'IIT Bombay',
        degree: 'M.Tech',
        fieldOfStudy: 'Computer Science and Engineering',
        startYear: 2004,
        endYear: 2006,
        current: false,
      },
    ],
    experience: [
      {
        company: 'Indian Institute of Technology Bombay',
        position: 'Professor',
        startDate: new Date('2017-01-01'),
        current: true,
        description:
          'Teaching advanced CS courses and managing credential verification committee.',
      },
      {
        company: 'IIT Bombay',
        position: 'Associate Professor',
        startDate: new Date('2011-08-01'),
        endDate: new Date('2016-12-31'),
        current: false,
        description: 'Taught undergraduate and graduate CS courses.',
      },
    ],
    achievements: [
      {
        title: 'Excellence in Teaching Award',
        issuer: 'IIT Bombay',
        date: new Date('2019-11-05'),
        description:
          'Recognized for outstanding teaching and student mentorship.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/drritusharma',
    },
    institution: 'Indian Institute of Technology Bombay',
    verificationAuthorityId: 'IITB-VER-023',
    department: 'Computer Science and Engineering',
    contactPhone: '+91-22-2576-7890',
    contactEmail: 'ritu.sharma@iitb.ac.in',
    officeLocation: 'CSE Department, Main Building',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator8,
    username: 'prof_deepa_nair',
    name: 'Prof. Deepa Nair',
    email: 'deepa.nair@iitm.ac.in',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=48',
    bio: 'Professor and credential verification committee head at IIT Madras. Expert in maintaining academic standards and credential integrity.',
    phoneNo: '+91-44-2257-8901',
    skills: [
      'Credential Verification',
      'Academic Standards',
      'Committee Leadership',
      'Quality Assurance',
      'Educational Assessment',
    ],
    education: [
      {
        institution: 'MIT, USA',
        degree: 'Ph.D.',
        fieldOfStudy: 'Electrical Engineering and Computer Science',
        startYear: 2005,
        endYear: 2010,
        current: false,
      },
      {
        institution: 'IIT Madras',
        degree: 'M.Tech',
        fieldOfStudy: 'Computer Science',
        startYear: 2003,
        endYear: 2005,
        current: false,
      },
    ],
    experience: [
      {
        company: 'Indian Institute of Technology Madras',
        position: 'Professor & Verification Committee Head',
        startDate: new Date('2016-06-01'),
        current: true,
        description:
          'Leading verification committee and teaching CS courses. Processed 1000+ credential verifications.',
      },
      {
        company: 'IIT Madras',
        position: 'Associate Professor',
        startDate: new Date('2010-08-01'),
        endDate: new Date('2016-05-31'),
        current: false,
        description: 'Research and teaching in computer science department.',
      },
    ],
    achievements: [
      {
        title: 'Outstanding Contribution to Academic Excellence',
        issuer: 'IIT Madras',
        date: new Date('2022-12-10'),
        description:
          'Recognized for maintaining highest standards in credential verification.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/profdeeepanair',
    },
    institution: 'Indian Institute of Technology Madras',
    verificationAuthorityId: 'IITM-VER-156',
    department: 'Computer Science and Engineering',
    contactPhone: '+91-44-2257-8901',
    contactEmail: 'deepa.nair@iitm.ac.in',
    officeLocation: 'CSE Building, Office 402',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator9,
    username: 'dr_vidya_desai',
    name: 'Dr. Vidya Desai',
    email: 'vidya.desai@dtu.ac.in',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=44',
    bio: 'Senior academic administrator with expertise in degree verification and maintaining institutional academic standards.',
    phoneNo: '+91-11-2787-1234',
    skills: [
      'Degree Verification',
      'Academic Administration',
      'Institutional Compliance',
      'Educational Standards',
      'Document Authentication',
    ],
    education: [
      {
        institution: 'Delhi Technological University',
        degree: 'Ph.D.',
        fieldOfStudy: 'Computer Engineering',
        startYear: 2007,
        endYear: 2012,
        current: false,
      },
      {
        institution: 'DTU',
        degree: 'M.Tech',
        fieldOfStudy: 'Software Engineering',
        startYear: 2005,
        endYear: 2007,
        current: false,
      },
    ],
    experience: [
      {
        company: 'Delhi Technological University',
        position: 'Dean Academic Affairs & Verifier',
        startDate: new Date('2018-01-01'),
        current: true,
        description:
          'Managing academic affairs and overseeing credential verification process university-wide.',
      },
      {
        company: 'DTU',
        position: 'Associate Professor',
        startDate: new Date('2012-08-01'),
        endDate: new Date('2017-12-31'),
        current: false,
        description:
          'Teaching and research in computer engineering department.',
      },
    ],
    achievements: [
      {
        title: 'Administrative Excellence Award',
        issuer: 'Delhi Technological University',
        date: new Date('2022-03-25'),
        description:
          'Recognized for streamlining academic verification processes.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/drvidyadesai',
    },
    institution: 'Delhi Technological University',
    verificationAuthorityId: 'DTU-VER-067',
    department: 'Academic Administration',
    contactPhone: '+91-11-2787-1234',
    contactEmail: 'vidya.desai@dtu.ac.in',
    officeLocation: 'Administrative Block',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator10,
    username: 'prof_sarika_pillai',
    name: 'Prof. Sarika Pillai',
    email: 'sarika.pillai@iitkgp.ac.in',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=46',
    bio: 'Professor leading credential verification division at IIT Kharagpur. Pioneering digital credential verification systems.',
    phoneNo: '+91-3222-28-3456',
    skills: [
      'Credential Verification',
      'Digital Authentication',
      'Blockchain for Credentials',
      'Academic Standards',
      'Technology Integration',
    ],
    education: [
      {
        institution: 'University of Cambridge',
        degree: 'Ph.D.',
        fieldOfStudy: 'Computer Science',
        startYear: 2004,
        endYear: 2009,
        current: false,
      },
      {
        institution: 'IIT Kharagpur',
        degree: 'M.Tech',
        fieldOfStudy: 'Computer Science and Engineering',
        startYear: 2002,
        endYear: 2004,
        current: false,
      },
    ],
    experience: [
      {
        company: 'Indian Institute of Technology Kharagpur',
        position: 'Professor & Head of Credential Division',
        startDate: new Date('2015-07-01'),
        current: true,
        description:
          'Leading credential verification division. Implementing blockchain-based verification system.',
      },
      {
        company: 'IIT Kharagpur',
        position: 'Associate Professor',
        startDate: new Date('2009-08-01'),
        endDate: new Date('2015-06-30'),
        current: false,
        description:
          'Teaching CS courses and conducting research in digital systems.',
      },
    ],
    achievements: [
      {
        title: 'Innovation in Academic Verification',
        issuer: 'IIT Kharagpur',
        date: new Date('2023-02-15'),
        description:
          'Developed blockchain-based credential verification system.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/profsarikapillai',
    },
    institution: 'Indian Institute of Technology Kharagpur',
    verificationAuthorityId: 'IITKGP-VER-190',
    department: 'Computer Science and Engineering',
    contactPhone: '+91-3222-28-3456',
    contactEmail: 'sarika.pillai@iitkgp.ac.in',
    officeLocation: 'CSE Department Head Office',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },

  // Additional Regulators for DigiLocker Institutions
  {
    _id: SEED_IDS.regulator11,
    username: 'dr_rajesh_nsdc',
    name: 'Dr. Rajesh Kumar',
    email: 'rajesh.kumar@nsdcindia.org',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=60',
    bio: 'Senior verification officer at NSDC, specializing in skill development certifications.',
    phoneNo: '+91-11-4915-4900',
    skills: [
      'Skill Certification',
      'PMKVY Verification',
      'Vocational Training Assessment',
    ],
    institution: 'NSDC (National Skill Development Corporation)',
    verificationAuthorityId: 'NSDC-VER-001',
    department: 'Certification Verification',
    contactPhone: '+91-11-4915-4900',
    contactEmail: 'rajesh.kumar@nsdcindia.org',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator12,
    username: 'prof_sharma_moe',
    name: 'Prof. Anita Sharma',
    email: 'anita.sharma@education.gov.in',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=48',
    bio: 'Ministry of Education certification officer, handling digital credential verification.',
    phoneNo: '+91-11-2338-5360',
    skills: [
      'Educational Credentials',
      'NSQF Verification',
      'Academic Standards',
    ],
    institution: 'Ministry of Education',
    verificationAuthorityId: 'MOE-VER-001',
    department: 'Digital Credentials Division',
    contactPhone: '+91-11-2338-5360',
    contactEmail: 'anita.sharma@education.gov.in',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator13,
    username: 'dr_patel_ignou',
    name: 'Dr. Suresh Patel',
    email: 'suresh.patel@ignou.ac.in',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=33',
    bio: 'IGNOU credential verification specialist for distance education programs.',
    phoneNo: '+91-11-2953-2835',
    skills: ['Distance Education', 'Degree Verification', 'SWAYAM Credentials'],
    institution: 'IGNOU',
    verificationAuthorityId: 'IGNOU-VER-001',
    department: 'Student Registration Division',
    contactPhone: '+91-11-2953-2835',
    contactEmail: 'suresh.patel@ignou.ac.in',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator14,
    username: 'prof_reddy_nptel',
    name: 'Prof. Ramesh Reddy',
    email: 'ramesh.reddy@nptel.ac.in',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=52',
    bio: 'NPTEL coordinator for online course certification and verification.',
    phoneNo: '+91-44-2257-8236',
    skills: ['Online Course Verification', 'MOOCs', 'Technical Certifications'],
    institution: 'NPTEL',
    verificationAuthorityId: 'NPTEL-VER-001',
    department: 'Certification Division',
    contactPhone: '+91-44-2257-8236',
    contactEmail: 'ramesh.reddy@nptel.ac.in',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator15,
    username: 'dr_gupta_nielit',
    name: 'Dr. Priya Gupta',
    email: 'priya.gupta@nielit.gov.in',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=49',
    bio: 'NIELIT verification officer for IT and electronics certifications.',
    phoneNo: '+91-11-2430-5800',
    skills: [
      'IT Certification',
      'CCC Verification',
      'Cyber Security Credentials',
    ],
    institution: 'NIELIT (National Institute of Electronics and IT)',
    verificationAuthorityId: 'NIELIT-VER-001',
    department: 'Certification Cell',
    contactPhone: '+91-11-2430-5800',
    contactEmail: 'priya.gupta@nielit.gov.in',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator16,
    username: 'prof_singh_aicte',
    name: 'Prof. Vikram Singh',
    email: 'vikram.singh@aicte-india.org',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=54',
    bio: 'AICTE certification coordinator for technical education programs.',
    phoneNo: '+91-11-2958-1000',
    skills: [
      'Technical Education',
      'AICTE Approvals',
      'Engineering Credentials',
    ],
    institution: 'AICTE (All India Council for Technical Education)',
    verificationAuthorityId: 'AICTE-VER-001',
    department: 'Accreditation & Verification',
    contactPhone: '+91-11-2958-1000',
    contactEmail: 'vikram.singh@aicte-india.org',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
  {
    _id: SEED_IDS.regulator17,
    username: 'dr_menon_swayam',
    name: 'Dr. Lakshmi Menon',
    email: 'lakshmi.menon@swayam.gov.in',
    password: 'password123',
    role: 'regulator',
    avatar: 'https://i.pravatar.cc/150?img=45',
    bio: 'SWAYAM program coordinator for online learning credential verification.',
    phoneNo: '+91-11-2674-9000',
    skills: [
      'MOOC Verification',
      'Online Learning',
      'SWAYAM Credentials',
      'Digital Certificates',
    ],
    institution: 'SWAYAM (Study Webs of Active Learning)',
    verificationAuthorityId: 'SWAYAM-VER-001',
    department: 'Online Certification Division',
    contactPhone: '+91-11-2674-9000',
    contactEmail: 'lakshmi.menon@swayam.gov.in',
    verifiedCount: 0,
    rejectedCount: 0,
    isPublic: true,
  },
];

// ==================== EMPLOYERS (10 users) ====================
const employers = [
  // DEMO USER 3: Meera Krishnan
  {
    _id: SEED_IDS.employer1,
    username: 'meera_krishnan',
    name: 'Meera Krishnan',
    email: 'meera.krishnan@startupx.io',
    password: 'password123',
    role: 'employer',
    avatar: 'https://i.pravatar.cc/150?img=20',
    bio: 'Co-founder and CTO of StartupX Technologies. Building innovative SaaS products.',
    phoneNo: '+91-22-3456-7890',
    skills: [
      'JavaScript',
      'Python',
      'Cloud Architecture',
      'Team Leadership',
      'Product Strategy',
      'SaaS',
      'Microservices',
      'DevOps',
    ],
    education: [
      {
        institution: 'IIT Bombay',
        degree: 'M.Tech',
        fieldOfStudy: 'Computer Science',
        startYear: 2008,
        endYear: 2010,
        current: false,
      },
      {
        institution: 'MIT College of Engineering',
        degree: 'Bachelor of Engineering',
        fieldOfStudy: 'Information Technology',
        startYear: 2004,
        endYear: 2008,
        current: false,
      },
    ],
    experience: [
      {
        company: 'StartupX Technologies',
        position: 'Co-founder & CTO',
        startDate: new Date('2018-03-01'),
        current: true,
        description:
          'Building innovative SaaS products for enterprise clients. Leading tech team of 25+ engineers.',
      },
      {
        company: 'TechCorp India',
        position: 'Senior Engineering Manager',
        startDate: new Date('2014-06-01'),
        endDate: new Date('2018-02-28'),
        current: false,
        description:
          'Led multiple product development teams. Scaled infrastructure to support 1M+ users.',
      },
    ],
    achievements: [
      {
        title: 'Top 50 Women in Tech India 2023',
        issuer: 'Tech Leadership Awards',
        date: new Date('2023-09-15'),
        description: 'Recognized for contributions to Indian tech ecosystem.',
      },
      {
        title: 'Innovation Award 2022',
        issuer: 'StartupX Technologies',
        date: new Date('2022-12-10'),
        description: 'Led development of AI-powered analytics platform.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/meerakrishnan',
      twitter: 'https://twitter.com/meera_tech',
      website: 'https://startupx.io',
    },
    // Employer-specific fields
    companyName: 'StartupX Technologies',
    industry: 'SaaS / Technology',
    companySize: '50-100',
    companyDescription:
      'Fast-growing startup building innovative SaaS products for enterprise clients. Focus on AI, blockchain, and IoT solutions. Dynamic work environment with equity options and unlimited learning opportunities.',
    companyLocation: 'Mumbai, India',
    isPublic: true,
  },
  {
    _id: SEED_IDS.employer2,
    username: 'rajesh_gupta',
    name: 'Rajesh Gupta',
    email: 'rajesh.gupta@techinnovate.com',
    password: 'password123',
    role: 'employer',
    avatar: 'https://i.pravatar.cc/150?img=14',
    bio: 'CEO of TechInnovate Solutions with 15+ years in IT services. Leading digital transformation initiatives for global enterprises.',
    phoneNo: '+91-80-4123-5678',
    skills: [
      'Leadership',
      'Digital Transformation',
      'Business Strategy',
      'Client Management',
      'Enterprise Solutions',
      'Cloud Computing',
      'Agile Methodology',
    ],
    education: [
      {
        institution: 'IIM Bangalore',
        degree: 'MBA',
        fieldOfStudy: 'Business Administration',
        startYear: 2005,
        endYear: 2007,
        current: false,
      },
      {
        institution: 'BITS Pilani',
        degree: 'B.E',
        fieldOfStudy: 'Computer Science',
        startYear: 2001,
        endYear: 2005,
        current: false,
      },
    ],
    experience: [
      {
        company: 'TechInnovate Solutions',
        position: 'CEO & Founder',
        startDate: new Date('2010-01-01'),
        current: true,
        description:
          'Founded and scaled company to 300+ employees. Delivered 200+ successful digital transformation projects.',
      },
      {
        company: 'Infosys Technologies',
        position: 'Project Manager',
        startDate: new Date('2007-08-01'),
        endDate: new Date('2009-12-31'),
        current: false,
        description:
          'Managed large-scale IT implementation projects for global clients.',
      },
    ],
    achievements: [
      {
        title: 'Entrepreneur of the Year 2022',
        issuer: 'Business India Awards',
        date: new Date('2022-11-20'),
        description: 'Recognized for building successful IT services company.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/rajeshgupta-ceo',
      twitter: 'https://twitter.com/rajesh_tech',
    },
    companyName: 'TechInnovate Solutions',
    industry: 'Information Technology',
    companySize: '200-500',
    companyDescription:
      'Leading IT services and consulting company specializing in digital transformation and enterprise software development.',
    companyLocation: 'Bangalore, India',
    isPublic: true,
  },
  {
    _id: SEED_IDS.employer3,
    username: 'aarti_deshmukh',
    name: 'Aarti Deshmukh',
    email: 'aarti.deshmukh@healthtech.io',
    password: 'password123',
    role: 'employer',
    avatar: 'https://i.pravatar.cc/150?img=32',
    bio: 'Head of Product at HealthTech Innovations. Building healthcare solutions that improve patient outcomes through technology.',
    phoneNo: '+91-44-8765-4321',
    skills: [
      'Product Management',
      'Healthcare Technology',
      'UX Design',
      'Data Analytics',
      'Regulatory Compliance',
      'Team Leadership',
      'Agile',
    ],
    education: [
      {
        institution: 'ISB Hyderabad',
        degree: 'MBA',
        fieldOfStudy: 'Product Management',
        startYear: 2013,
        endYear: 2014,
        current: false,
      },
      {
        institution: 'NIT Trichy',
        degree: 'B.Tech',
        fieldOfStudy: 'Biomedical Engineering',
        startYear: 2009,
        endYear: 2013,
        current: false,
      },
    ],
    experience: [
      {
        company: 'HealthTech Innovations',
        position: 'VP Product',
        startDate: new Date('2019-03-01'),
        current: true,
        description:
          'Leading product strategy for telemedicine and patient management platforms. Scaled user base to 500K+ patients.',
      },
      {
        company: 'MedTech Solutions',
        position: 'Senior Product Manager',
        startDate: new Date('2014-09-01'),
        endDate: new Date('2019-02-28'),
        current: false,
        description:
          'Managed healthcare SaaS products and led cross-functional teams.',
      },
    ],
    achievements: [
      {
        title: 'Healthcare Innovation Award',
        issuer: 'HealthTech Summit',
        date: new Date('2023-06-10'),
        description:
          'Recognized for developing patient-centric telemedicine platform.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/aartideshmukh',
    },
    companyName: 'HealthTech Innovations',
    industry: 'Healthcare Technology',
    companySize: '100-200',
    companyDescription:
      'Healthcare technology company revolutionizing patient care through digital innovation.',
    companyLocation: 'Chennai, India',
    isPublic: true,
  },
  {
    _id: SEED_IDS.employer4,
    username: 'nikhil_shah',
    name: 'Nikhil Shah',
    email: 'nikhil.shah@financeai.com',
    password: 'password123',
    role: 'employer',
    avatar: 'https://i.pravatar.cc/150?img=69',
    bio: 'Chief Product Officer at FinanceAI Technologies. Expert in building AI-powered financial products and driving product innovation.',
    phoneNo: '+91-22-7654-3210',
    skills: [
      'Product Strategy',
      'FinTech',
      'AI/ML Products',
      'Financial Services',
      'Risk Management',
      'Team Building',
      'Data-Driven Decisions',
    ],
    education: [
      {
        institution: 'Harvard Business School',
        degree: 'MBA',
        fieldOfStudy: 'Finance & Technology',
        startYear: 2011,
        endYear: 2013,
        current: false,
      },
      {
        institution: 'IIT Delhi',
        degree: 'B.Tech',
        fieldOfStudy: 'Computer Science',
        startYear: 2007,
        endYear: 2011,
        current: false,
      },
    ],
    experience: [
      {
        company: 'FinanceAI Technologies',
        position: 'Chief Product Officer',
        startDate: new Date('2018-06-01'),
        current: true,
        description:
          'Leading product development for AI-powered lending and investment platforms. Managing 10M+ user base.',
      },
      {
        company: 'PayTech Global',
        position: 'VP Product',
        startDate: new Date('2013-08-01'),
        endDate: new Date('2018-05-31'),
        current: false,
        description:
          'Built digital payment solutions and managed product lifecycle.',
      },
    ],
    achievements: [
      {
        title: 'FinTech Leader of the Year',
        issuer: 'FinTech Awards India',
        date: new Date('2022-10-15'),
        description:
          'Recognized for innovation in AI-powered financial products.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/nikhilshah-cpo',
      twitter: 'https://twitter.com/nikhil_fintech',
    },
    companyName: 'FinanceAI Technologies',
    industry: 'FinTech',
    companySize: '200-500',
    companyDescription:
      'FinTech company using AI and machine learning for intelligent financial solutions.',
    companyLocation: 'Mumbai, India',
    isPublic: true,
  },
  {
    _id: SEED_IDS.employer5,
    username: 'ritu_agarwal',
    name: 'Ritu Agarwal',
    email: 'ritu.agarwal@ecommerce.in',
    password: 'password123',
    role: 'employer',
    avatar: 'https://i.pravatar.cc/150?img=36',
    bio: 'VP of Technology at ShopEase E-Commerce. Building scalable e-commerce platforms serving millions of customers daily.',
    phoneNo: '+91-80-9876-5432',
    skills: [
      'Technology Leadership',
      'E-Commerce Platforms',
      'Scalable Architecture',
      'Team Management',
      'Cloud Infrastructure',
      'Microservices',
      'DevOps',
    ],
    education: [
      {
        institution: 'Stanford University',
        degree: 'MS',
        fieldOfStudy: 'Computer Science',
        startYear: 2010,
        endYear: 2012,
        current: false,
      },
      {
        institution: 'IIT Kanpur',
        degree: 'B.Tech',
        fieldOfStudy: 'Computer Science and Engineering',
        startYear: 2006,
        endYear: 2010,
        current: false,
      },
    ],
    experience: [
      {
        company: 'ShopEase E-Commerce',
        position: 'VP of Technology',
        startDate: new Date('2017-01-01'),
        current: true,
        description:
          'Leading tech team of 150+ engineers. Built platform handling 50M+ monthly transactions.',
      },
      {
        company: 'Amazon India',
        position: 'Senior Engineering Manager',
        startDate: new Date('2012-09-01'),
        endDate: new Date('2016-12-31'),
        current: false,
        description: 'Managed e-commerce platform development teams.',
      },
    ],
    achievements: [
      {
        title: 'Women in Tech Leadership Award',
        issuer: 'Tech Excellence Forum',
        date: new Date('2023-03-08'),
        description: 'Recognized for outstanding leadership in technology.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/rituagarwal-vp',
      twitter: 'https://twitter.com/ritu_tech',
    },
    companyName: 'ShopEase E-Commerce',
    industry: 'E-Commerce',
    companySize: '500-1000',
    companyDescription:
      'Leading e-commerce platform connecting buyers and sellers across India.',
    companyLocation: 'Bangalore, India',
    isPublic: true,
  },
  {
    _id: SEED_IDS.employer6,
    username: 'lakshmi_rao',
    name: 'Lakshmi Rao',
    email: 'lakshmi.rao@dataanalytics.io',
    password: 'password123',
    role: 'employer',
    avatar: 'https://i.pravatar.cc/150?img=27',
    bio: 'Chief Data Officer at DataAnalytics Pro. Leading data-driven transformation for enterprises globally.',
    phoneNo: '+91-40-5678-9012',
    skills: [
      'Data Strategy',
      'Business Intelligence',
      'Analytics',
      'Big Data',
      'ML/AI',
      'Leadership',
      'Data Governance',
      'Tableau',
      'Power BI',
    ],
    education: [
      {
        institution: 'MIT Sloan',
        degree: 'MBA',
        fieldOfStudy: 'Analytics',
        startYear: 2012,
        endYear: 2014,
        current: false,
      },
      {
        institution: 'IIT Hyderabad',
        degree: 'B.Tech',
        fieldOfStudy: 'Computer Science',
        startYear: 2008,
        endYear: 2012,
        current: false,
      },
    ],
    experience: [
      {
        company: 'DataAnalytics Pro',
        position: 'Chief Data Officer',
        startDate: new Date('2018-05-01'),
        current: true,
        description:
          'Leading data strategy and analytics for 100+ enterprise clients. Built analytics platform processing 10TB+ daily.',
      },
      {
        company: 'McKinsey & Company',
        position: 'Analytics Consultant',
        startDate: new Date('2014-08-01'),
        endDate: new Date('2018-04-30'),
        current: false,
        description:
          'Provided data analytics consulting to Fortune 500 companies.',
      },
    ],
    achievements: [
      {
        title: 'Data Leader of the Year',
        issuer: 'Analytics Excellence Awards',
        date: new Date('2023-05-20'),
        description: 'Recognized for driving data-driven transformation.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/lakshmi-rao-cdo',
    },
    companyName: 'DataAnalytics Pro',
    industry: 'Data Analytics',
    companySize: '200-500',
    companyDescription:
      'Data analytics and business intelligence solutions provider helping enterprises make data-driven decisions.',
    companyLocation: 'Hyderabad, India',
    isPublic: true,
  },
  {
    _id: SEED_IDS.employer7,
    username: 'varun_pillai',
    name: 'Varun Pillai',
    email: 'varun.pillai@gamesstudio.com',
    password: 'password123',
    role: 'employer',
    avatar: 'https://i.pravatar.cc/150?img=61',
    bio: 'Creative Director at GameForge Studios. Creating award-winning games with focus on storytelling and immersive gameplay.',
    phoneNo: '+91-22-8765-4321',
    skills: [
      'Game Design',
      'Creative Direction',
      'Unity',
      'Unreal Engine',
      'Team Leadership',
      'Storytelling',
      'Game Mechanics',
      'Project Management',
    ],
    education: [
      {
        institution: 'USC School of Cinematic Arts',
        degree: 'MFA',
        fieldOfStudy: 'Interactive Media & Games',
        startYear: 2009,
        endYear: 2011,
        current: false,
      },
      {
        institution: 'NID Ahmedabad',
        degree: 'Bachelor of Design',
        fieldOfStudy: 'Animation Film Design',
        startYear: 2005,
        endYear: 2009,
        current: false,
      },
    ],
    experience: [
      {
        company: 'GameForge Studios',
        position: 'Creative Director & Co-founder',
        startDate: new Date('2015-03-01'),
        current: true,
        description:
          'Leading creative vision for 10+ AAA mobile games. Won multiple industry awards.',
      },
      {
        company: 'Ubisoft India',
        position: 'Senior Game Designer',
        startDate: new Date('2011-09-01'),
        endDate: new Date('2015-02-28'),
        current: false,
        description: 'Designed game mechanics and narrative for mobile titles.',
      },
    ],
    achievements: [
      {
        title: 'Best Mobile Game Award',
        issuer: 'IGDC India',
        date: new Date('2022-11-18'),
        description: 'Won for innovative storytelling in mobile gaming.',
      },
      {
        title: 'Game Developer of the Year',
        issuer: 'Game Awards India',
        date: new Date('2023-07-25'),
        description: 'Recognized for contribution to Indian gaming industry.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/varun-pillai-games',
      twitter: 'https://twitter.com/varun_gamedev',
    },
    companyName: 'GameForge Studios',
    industry: 'Gaming',
    companySize: '100-200',
    companyDescription:
      'Award-winning game development studio creating immersive gaming experiences.',
    companyLocation: 'Mumbai, India',
    isPublic: true,
  },
  {
    _id: SEED_IDS.employer8,
    username: 'manish_bose',
    name: 'Manish Bose',
    email: 'manish.bose@edutech.com',
    password: 'password123',
    role: 'employer',
    avatar: 'https://i.pravatar.cc/150?img=62',
    bio: 'Co-founder of EduTech Learning Platform. Democratizing education through technology and AI-powered learning.',
    phoneNo: '+91-33-2345-6789',
    skills: [
      'EdTech',
      'Product Development',
      'Educational Content',
      'AI/ML',
      'Business Strategy',
      'Team Building',
      'Fundraising',
      'Marketing',
    ],
    education: [
      {
        institution: 'IIM Calcutta',
        degree: 'MBA',
        fieldOfStudy: 'Entrepreneurship',
        startYear: 2010,
        endYear: 2012,
        current: false,
      },
      {
        institution: 'Jadavpur University',
        degree: 'B.Tech',
        fieldOfStudy: 'Computer Science',
        startYear: 2006,
        endYear: 2010,
        current: false,
      },
    ],
    experience: [
      {
        company: 'EduTech Learning Platform',
        position: 'Co-founder & CEO',
        startDate: new Date('2016-01-01'),
        current: true,
        description:
          'Built online learning platform serving 2M+ students. Raised $25M in funding.',
      },
      {
        company: 'Pearson India',
        position: 'Product Manager',
        startDate: new Date('2012-08-01'),
        endDate: new Date('2015-12-31'),
        current: false,
        description: 'Managed digital learning products for K-12 segment.',
      },
    ],
    achievements: [
      {
        title: 'EdTech Innovator Award',
        issuer: 'Education Innovation Summit',
        date: new Date('2023-04-12'),
        description: 'Recognized for making quality education accessible.',
      },
      {
        title: '40 Under 40 Entrepreneurs',
        issuer: 'Fortune India',
        date: new Date('2022-09-05'),
        description: 'Featured in list of top young entrepreneurs.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/manishbose-edutech',
      twitter: 'https://twitter.com/manish_edutech',
    },
    companyName: 'EduTech Learning Platform',
    industry: 'Education Technology',
    companySize: '100-200',
    companyDescription:
      'Making quality education accessible through technology with AI-powered personalized learning paths.',
    companyLocation: 'Kolkata, India',
    isPublic: true,
  },
  {
    _id: SEED_IDS.employer9,
    username: 'sneha_kulkarni_employer',
    name: 'Sneha Kulkarni',
    email: 'sneha.kulkarni@webtech.in',
    password: 'password123',
    role: 'employer',
    avatar: 'https://i.pravatar.cc/150?img=45',
    bio: 'Founder and Lead Designer at WebTech Solutions. Creating stunning web experiences with focus on user-centered design.',
    phoneNo: '+91-20-9876-5432',
    skills: [
      'Web Design',
      'UX/UI',
      'Creative Direction',
      'Team Management',
      'Client Relations',
      'Front-end Development',
      'Branding',
      'Figma',
    ],
    education: [
      {
        institution: 'NID Ahmedabad',
        degree: 'Master of Design',
        fieldOfStudy: 'Interaction Design',
        startYear: 2011,
        endYear: 2013,
        current: false,
      },
      {
        institution: 'COEP Pune',
        degree: 'B.E',
        fieldOfStudy: 'Computer Engineering',
        startYear: 2007,
        endYear: 2011,
        current: false,
      },
    ],
    experience: [
      {
        company: 'WebTech Solutions',
        position: 'Founder & Lead Designer',
        startDate: new Date('2015-06-01'),
        current: true,
        description:
          'Founded award-winning web agency. Delivered 200+ successful projects for global clients.',
      },
      {
        company: 'Ogilvy Digital',
        position: 'Senior UX Designer',
        startDate: new Date('2013-07-01'),
        endDate: new Date('2015-05-31'),
        current: false,
        description: 'Designed digital experiences for leading brands.',
      },
    ],
    achievements: [
      {
        title: 'Best Web Design Agency',
        issuer: 'Web Excellence Awards',
        date: new Date('2023-01-15'),
        description: 'Won for outstanding web design and user experience.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/sneha-kulkarni-design',
      behance: 'https://behance.net/snehakulkarni',
      portfolio: 'https://webtechsolutions.in',
    },
    companyName: 'WebTech Solutions',
    industry: 'Web Development',
    companySize: '100-200',
    companyDescription:
      'Full-service web development agency creating stunning websites and web applications.',
    companyLocation: 'Pune, India',
    isPublic: true,
  },
  {
    _id: SEED_IDS.employer10,
    username: 'amit_verma',
    name: 'Amit Verma',
    email: 'amit.verma@cloudcorp.com',
    password: 'password123',
    role: 'employer',
    avatar: 'https://i.pravatar.cc/150?img=51',
    bio: 'VP of Engineering at CloudCorp India. Leading cloud transformation initiatives for Fortune 500 companies.',
    phoneNo: '+91-120-456-7890',
    skills: [
      'Cloud Architecture',
      'Engineering Leadership',
      'AWS',
      'Azure',
      'GCP',
      'DevOps',
      'Kubernetes',
      'Team Scaling',
      'Technical Strategy',
    ],
    education: [
      {
        institution: 'Carnegie Mellon University',
        degree: 'MS',
        fieldOfStudy: 'Computer Science',
        startYear: 2008,
        endYear: 2010,
        current: false,
      },
      {
        institution: 'IIT Roorkee',
        degree: 'B.Tech',
        fieldOfStudy: 'Computer Science and Engineering',
        startYear: 2004,
        endYear: 2008,
        current: false,
      },
    ],
    experience: [
      {
        company: 'CloudCorp India',
        position: 'VP of Engineering',
        startDate: new Date('2016-04-01'),
        current: true,
        description:
          'Leading engineering org of 400+ engineers. Architected cloud solutions for 50+ enterprise clients.',
      },
      {
        company: 'Microsoft India',
        position: 'Principal Engineering Manager',
        startDate: new Date('2010-09-01'),
        endDate: new Date('2016-03-31'),
        current: false,
        description: 'Led Azure platform development teams in India.',
      },
    ],
    achievements: [
      {
        title: 'Cloud Architect of the Year',
        issuer: 'Cloud Summit Asia',
        date: new Date('2022-08-20'),
        description:
          'Recognized for excellence in cloud architecture and leadership.',
      },
      {
        title: 'AWS Partner Award',
        issuer: 'Amazon Web Services',
        date: new Date('2023-06-15'),
        description: 'Received for outstanding cloud solutions delivery.',
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/amit-verma-vp',
      twitter: 'https://twitter.com/amit_cloud',
    },
    companyName: 'CloudCorp India',
    industry: 'Cloud Computing',
    companySize: '500-1000',
    companyDescription:
      'Premier cloud solutions provider offering AWS, Azure, and GCP services.',
    companyLocation: 'Gurgaon, India',
    isPublic: true,
  },
];

// Combine all users
const users = [...learners, ...regulators, ...employers];

export const seedUsers = async () => {
  const usersWithHashedPasswords = await Promise.all(
    users.map(async (user) => {
      const salt = await bcrypt.genSalt(10);
      const passwordHash = await bcrypt.hash(user.password, salt);
      const { password, ...userWithoutPassword } = user;
      return {
        ...userWithoutPassword,
        passwordHash,
      };
    }),
  );

  const createdUsers = await User.insertMany(usersWithHashedPasswords);
  console.log(
    `✅ Users created: ${createdUsers.length} (10 learners, 10 regulators, 10 employers)`,
  );
  return createdUsers;
};
