// List of Indian Educational Institutions for Regulator Verification
export const INDIAN_INSTITUTIONS = [
  // IITs
  'IIT Delhi',
  'IIT Bombay',
  'IIT Madras',
  'IIT Kanpur',
  'IIT Kharagpur',
  'IIT Roorkee',
  'IIT Guwahati',
  'IIT Hyderabad',
  'IIT Indore',
  'IIT Bhubaneswar',
  'IIT Gandhinagar',
  'IIT Patna',
  'IIT Ropar',
  'IIT Mandi',
  'IIT (BHU) Varanasi',
  'IIT Jodhpur',
  'IIT Palakkad',
  'IIT Tirupati',
  'IIT Dhanbad (ISM)',
  'IIT Bhilai',
  'IIT Goa',
  'IIT Jammu',
  'IIT Dharwad',
  
  // NITs
  'NIT Trichy',
  'NIT Surathkal',
  'NIT Warangal',
  'NIT Calicut',
  'NIT Rourkela',
  'NIT Kurukshetra',
  'NIT Nagpur',
  'NIT Durgapur',
  'NIT Jaipur',
  'NIT Bhopal',
  'NIT Allahabad',
  'NIT Surat',
  'NIT Silchar',
  'NIT Hamirpur',
  'NIT Jalandhar',
  'NIT Patna',
  'NIT Raipur',
  'NIT Agartala',
  'NIT Arunachal Pradesh',
  'NIT Delhi',
  'NIT Goa',
  'NIT Manipur',
  'NIT Meghalaya',
  'NIT Mizoram',
  'NIT Nagaland',
  'NIT Puducherry',
  'NIT Sikkim',
  'NIT Srinagar',
  'NIT Uttarakhand',
  'NIT Andhra Pradesh',
  
  // IIITs
  'IIIT Hyderabad',
  'IIIT Bangalore',
  'IIIT Delhi',
  'IIIT Allahabad',
  'IIIT Gwalior',
  'IIIT Jabalpur',
  'IIIT Kancheepuram',
  'IIIT Lucknow',
  'IIIT Nagpur',
  'IIIT Pune',
  'IIIT Vadodara',
  'IIIT Kota',
  'IIIT Sonepat',
  'IIIT Kalyani',
  'IIIT Tiruchirappalli',
  'IIIT Una',
  'IIIT Surat',
  'IIIT Manipur',
  'IIIT Kottayam',
  'IIIT Ranchi',
  'IIIT Bhagalpur',
  'IIIT Bhopal',
  'IIIT Dharwad',
  'IIIT Raichur',
  
  // Central Universities
  'Delhi University',
  'Jawaharlal Nehru University',
  'Banaras Hindu University',
  'Aligarh Muslim University',
  'Jamia Millia Islamia',
  'University of Hyderabad',
  'Pondicherry University',
  'Tezpur University',
  'North Eastern Hill University',
  'Assam University',
  
  // State Universities (Top)
  'Anna University',
  'Mumbai University',
  'Pune University',
  'Calcutta University',
  'Madras University',
  'Osmania University',
  'Andhra University',
  'Bangalore University',
  'Kerala University',
  'Cochin University of Science and Technology',
  
  // Deemed Universities
  'BITS Pilani',
  'Manipal Academy of Higher Education',
  'Vellore Institute of Technology (VIT)',
  'Thapar Institute of Engineering and Technology',
  'SRM Institute of Science and Technology',
  'Amity University',
  'Kalinga Institute of Industrial Technology (KIIT)',
  'Birla Institute of Technology',
  'Jadavpur University',
  'PSG College of Technology',
  
  // Others
  'Indian Statistical Institute',
  'International Institute of Information Technology',
  'Institute of Chemical Technology',
  'Dhirubhai Ambani Institute of Information and Communication Technology',
  'Indraprastha Institute of Information Technology Delhi',
  'Netaji Subhas University of Technology',
  'Delhi Technological University',
  'Jamia Hamdard',
  'Nirma University',
  'PES University',
  'RV College of Engineering',
  'MS Ramaiah Institute of Technology',
  'BMSCE Bangalore',
  'Dayananda Sagar College of Engineering',
  'BMS College of Engineering',
  'CMR Institute of Technology',
  'The LNM Institute of Information Technology',
  'Visvesvaraya National Institute of Technology',
  'Maulana Azad National Institute of Technology',
  'Motilal Nehru National Institute of Technology',
  'Sardar Vallabhbhai National Institute of Technology',
  'Dr. B R Ambedkar National Institute of Technology',
  'Malaviya National Institute of Technology',
  
  // Specialized Institutes
  'Indian Institute of Science',
  'Indian School of Business',
  'National Institute of Design',
  'National Institute of Fashion Technology',
  'Symbiosis International University',
  'XLRI Jamshedpur',
  'Indian Institute of Management Ahmedabad',
  'Indian Institute of Management Bangalore',
  'Indian Institute of Management Calcutta',
  'Indian Institute of Management Lucknow',
  'Indian Institute of Management Indore',
  'Indian Institute of Management Kozhikode',
  
  // Open Universities
  'IGNOU (Indira Gandhi National Open University)',
  'Dr. B.R. Ambedkar Open University',
  'Netaji Subhas Open University',
  'Tamil Nadu Open University',
  'Karnataka State Open University',
  'MP Bhoj Open University',
  
  // Other
  'Other Institution',
];

export default INDIAN_INSTITUTIONS;
